### ISSUE TITLE
TokyoDisneyResortMagicKingdom and TokyoDisneyResortDisneySea not show GetWaitTimes()

### ISSUE THREAD

**Issue by Zeusgod7** [cubehouse/themeparks#100]
// access a specific park
var disneyMagicKingdom = new Themeparks.Parks.TokyoDisneyResortDisneySea();

// access wait times by Promise
disneyMagicKingdom.GetWaitTimes().then(function(rides) {
    // print each wait time
    for(var i=0, ride; ride=rides[i++];) {
        console.log(ride.name + ": " + ride.waitTime + " minutes wait");
    }
}, console.error);

has some reject message:

(node:18840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to find GPS Cookie from TDR website
(node:18840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks!!

**Comment by cubehouse** [comment]
Issue 100!!!

Looks like their cookie setting page has changed. Will see if I can figure it out.

**Comment by Zeusgod7** [comment]
Thanks a lot !!

**Comment by cubehouse** [comment]
Published fix in 4.6.7. The geo-location checking page on their website moved, so just had to figure it out again.
