### ISSUE TITLE
Bug timezone sixflags parks

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#101]
Hello,
Sixflag Fleet Opening Hours Recovery API does not get the date back to the right format

date retrieved from API:
2018-03-12T05:30:00-05:00
real date :
2018-03-12T10:30:00-05:00
the API removes the 5 hour shift instead of displaying the local time + timezone

![sans titre](https://user-images.githubusercontent.com/441244/37300337-006a1b6c-2626-11e8-9570-a9d9b46cf466.png)

this problem only occurs on sixflags

**Comment by cubehouse** [comment]
I believe I've fixed this in the latest publish.

Please supply sample code (or even better, a pull request with a fix yourself) if you can for any future bugs to make it easier to understand the issue :)

Thanks!
