### ISSUE TITLE
TokyoDisneyResortDisneySea & TokyoDisneyResortMagicKingdom all return 0 minutes wait

### ISSUE THREAD

**Issue by Zeusgod7** [cubehouse/themeparks#106]
var Themeparks = require("themeparks");
var disneyMagicKingdom = new Themeparks.Parks.TokyoDisneyResortMagicKingdom;
disneyMagicKingdom.GetWaitTimes().then(function(rides) {
    // print each wait time
    for(var i=0, ride; ride=rides[i++];) {
        console.log(ride.name + ": " + ride.waitTime + " minutes wait");
    }
}, console.error);

==== No Error , But all return 0 minutes wait ====
Omnibus: 0 minutes wait
Pirates of the Caribbean: 0 minutes wait
Jungle Cruise: Wildlife Expeditions: 0 minutes wait
Western River Railroad: 0 minutes wait
Swiss Family Treehouse: 0 minutes wait
The Enchanted Tiki Room: Stitch Presents "Aloha E Komo Mai!": 0 minutes wait
Westernland Shootin' Gallery: 0 minutes wait
Country Bear Theater: 0 minutes wait
Mark Twain Riverboat: 0 minutes wait
Big Thunder Mountain: 0 minutes wait
Tom Sawyer Island Rafts: 0 minutes wait
Splash Mountain: 0 minutes wait
Beaver Brothers Explorer Canoes: 0 minutes wait
Peter Pan's Flight: 0 minutes wait
Snow White's Adventures: 0 minutes wait
Cinderella's Fairy Tale Hall: 0 minutes wait
Mickey's PhilharMagic: 0 minutes wait
Pinocchio's Daring Journey: 0 minutes wait
Dumbo The Flying Elephant: 0 minutes wait
Castle Carrousel: 0 minutes wait
Haunted Mansion: 0 minutes wait
"it's a small world" (Reopens on April 15, 2018): 0 minutes wait
Alice's Tea Party: 0 minutes wait
Pooh's Hunny Hunt: 0 minutes wait
Roger Rabbit's Car Toon Spin: 0 minutes wait
Minnie's House: 0 minutes wait
Chip 'n Dale's Treehouse: 0 minutes wait
Gadget's Go Coaster: 0 minutes wait
Donald's Boat: 0 minutes wait
Goofy's Paint 'n' Play House: 0 minutes wait
Star Tours: The Adventures Continue: 0 minutes wait
Space Mountain: 0 minutes wait
Buzz Lightyear's Astro Blasters: 0 minutes wait
Monsters, Inc. Ride &amp; Go Seek!: 0 minutes wait
Penny Arcade: 0 minutes wait
Toon Park: 0 minutes wait
Stitch Encounter: 0 minutes wait
==== No Error , End ====

Thanks!

**Comment by CoryFailM3** [comment]
Could it be a timezone issue? Have you tried it during the Japan peak hours?

**Comment by Zeusgod7** [comment]
Sorry! update to 4.6.13 it is work, Thanks! ^^
