### ISSUE TITLE
Tokyo Disneyland Resort times failing?

### ISSUE THREAD

**Issue by dotaguro** [cubehouse/themeparks#110]
I'm seeing Error fetching park wait times: Unable to parse  into a JSON object when trying to get data for the Tokyo Disney resorts. Known issue or just something on my end?

**Comment by cubehouse** [comment]
What version of the library are you using?

**Comment by dotaguro** [comment]
Head from https://github.com/cubehouse/themeparks. I think that's 4.9.13

**Comment by dotaguro** [comment]
Sorry, 4.6.14.

**Comment by cubehouse** [comment]
Looks like they've completely shut off their API.
Here is a quick patch for getting the wait times running again, need to figure out how to get the English ride names back, and then re-do the calendar too.
https://gist.github.com/cubehouse/615109ad4aa15bd67672410bb6158a9f

**Comment by dotaguro** [comment]
Thanks for the patch. I don't know if it'll help, but I speak Japanese so I've attached a CSV mapping the Japanese kana names for the two parks back into the English language names that were used before the API died. 

I don't know if you really want to just hardcode the conversion, but it might help?


[Disney Resort Mapping - Sheet1.csv.txt](https://github.com/cubehouse/themeparks/files/2087382/Disney.Resort.Mapping.-.Sheet1.csv.txt)

**Comment by cubehouse** [comment]
I've published the fix in 4.6.16

Sorry for the delay! Been very busy.

This was caused because we were relying on their old API for ride data, which they turned off. I've had to parse their site's HTML manually to get the data we need, but it all seems to be working again now. Let me know if it's fixed for you.
