### ISSUE TITLE
Asterix coasters are "Closed"

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#113]
Hello everyone ! 
The Asterix park has his coasters "Closed", but, in the Asterix Park's app, the coasters was open, and have wait times...

How to fix it ?

Cordially,
Louis FORAUX
******
__ I'm sorry, I'm french, my english is not perfect :)

**Comment by cubehouse** [comment]
Hey Louis,

Thanks for reporting the issue. If you can, have a dive into the code and see what's going on. I suspect their app has changed though, which may be a little difficult to figure it out.

Otherwise, I'll try and have a look over the next few days when I get a moment,

**Comment by cubehouse** [comment]
Fixed and published in 4.6.17.

Thanks for your report!
