### ISSUE TITLE
TokyoDisneyResortMagicKingdom & TokyoDisneyResortDisneySea unavailable

### ISSUE THREAD

**Issue by nppi3enz** [cubehouse/themeparks#114]
```
var park = new Themeparks.Parks.TokyoDisneyResortDisneySea();

// get park opening times
park.GetOpeningTimes().then(function(times) {
    // print opening times
    for(var i=0, time; time=times[i++];) {
        if (time.type == "Operating") {
            console.log("[" + time.date + "] Open from " + time.openingTime +
 " until " + time.closingTime);
        }
    }
}, console.error);


```

It show result

> .....
> <br />
> This site is temporarily unavailable.<br />
> Please try back again later.</p></div>
> </div>
> .....

![screen shot 2018-06-28 at 2 26 44 am](https://user-images.githubusercontent.com/7631931/41995101-c1abd06a-7a7a-11e8-9e07-c4cfaea57c37.png)

**Comment by cubehouse** [comment]
Hi,

What version of the library are you using?

**Comment by nppi3enz** [comment]
4.6.14

**Comment by cubehouse** [comment]
Please try updating to the latest version and try again

**Comment by cubehouse** [comment]
See changelog, there had been a change in Disney Tokyo API that required an update to the library since 4.6.14:

https://github.com/cubehouse/themeparks/blob/master/CHANGELOG.md

**Comment by nppi3enz** [comment]
i'm already update to version 4.7
It's show
> Error fetching park wait times: Unable to extract blockId and pageBlockId from Tokyo Disneyland page

**Comment by cubehouse** [comment]
Can you run this and confirm it works?

npm i themeparks@4.7.0 mocha && PARKID=TokyoDisneyResortDisneySea PRINTDATA=true node_modules/.bin/mocha node_modules/themeparks/dist/testonline.js

I am running this on a fresh docker instance and not seeing any issues.

**Comment by nppi3enz** [comment]
`

  Park TokyoDisneyResortDisneySea
    Get Park Wait Times
undefined
      1) should not return an error fetching ride times
      2) should have some ride data
      3) should have an ID for every ride
      4) should have a wait time for every ride
      5) should have a name for every ride
      6) should have an active state for every ride
      7) should have a fastpass field for every ride
      8) should have a status field for every ride
      9) should have matching status and active fields
    Get Schedule
[
  {
    "date": "2018-06-28",
    "openingTime": "2018-06-28T23:59:59+09:00",
    "closingTime": "2018-06-28T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-06-29",
    "openingTime": "2018-06-29T23:59:59+09:00",
    "closingTime": "2018-06-29T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-06-30",
    "openingTime": "2018-06-30T23:59:59+09:00",
    "closingTime": "2018-06-30T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-01",
    "openingTime": "2018-07-01T23:59:59+09:00",
    "closingTime": "2018-07-01T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-02",
    "openingTime": "2018-07-02T23:59:59+09:00",
    "closingTime": "2018-07-02T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-03",
    "openingTime": "2018-07-03T23:59:59+09:00",
    "closingTime": "2018-07-03T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-04",
    "openingTime": "2018-07-04T23:59:59+09:00",
    "closingTime": "2018-07-04T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-05",
    "openingTime": "2018-07-05T23:59:59+09:00",
    "closingTime": "2018-07-05T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-06",
    "openingTime": "2018-07-06T23:59:59+09:00",
    "closingTime": "2018-07-06T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-07",
    "openingTime": "2018-07-07T23:59:59+09:00",
    "closingTime": "2018-07-07T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-08",
    "openingTime": "2018-07-08T23:59:59+09:00",
    "closingTime": "2018-07-08T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-09",
    "openingTime": "2018-07-09T23:59:59+09:00",
    "closingTime": "2018-07-09T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-10",
    "openingTime": "2018-07-10T23:59:59+09:00",
    "closingTime": "2018-07-10T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-11",
    "openingTime": "2018-07-11T23:59:59+09:00",
    "closingTime": "2018-07-11T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-12",
    "openingTime": "2018-07-12T23:59:59+09:00",
    "closingTime": "2018-07-12T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-13",
    "openingTime": "2018-07-13T23:59:59+09:00",
    "closingTime": "2018-07-13T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-14",
    "openingTime": "2018-07-14T23:59:59+09:00",
    "closingTime": "2018-07-14T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-15",
    "openingTime": "2018-07-15T23:59:59+09:00",
    "closingTime": "2018-07-15T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-16",
    "openingTime": "2018-07-16T23:59:59+09:00",
    "closingTime": "2018-07-16T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-17",
    "openingTime": "2018-07-17T23:59:59+09:00",
    "closingTime": "2018-07-17T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-18",
    "openingTime": "2018-07-18T23:59:59+09:00",
    "closingTime": "2018-07-18T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-19",
    "openingTime": "2018-07-19T23:59:59+09:00",
    "closingTime": "2018-07-19T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-20",
    "openingTime": "2018-07-20T23:59:59+09:00",
    "closingTime": "2018-07-20T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-21",
    "openingTime": "2018-07-21T23:59:59+09:00",
    "closingTime": "2018-07-21T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-22",
    "openingTime": "2018-07-22T23:59:59+09:00",
    "closingTime": "2018-07-22T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-23",
    "openingTime": "2018-07-23T23:59:59+09:00",
    "closingTime": "2018-07-23T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-24",
    "openingTime": "2018-07-24T23:59:59+09:00",
    "closingTime": "2018-07-24T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-25",
    "openingTime": "2018-07-25T23:59:59+09:00",
    "closingTime": "2018-07-25T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-26",
    "openingTime": "2018-07-26T23:59:59+09:00",
    "closingTime": "2018-07-26T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-27",
    "openingTime": "2018-07-27T23:59:59+09:00",
    "closingTime": "2018-07-27T23:59:59+09:00",
    "type": "Closed"
  },
  {
    "date": "2018-07-28",
    "openingTime": "2018-07-28T23:59:59+09:00",
    "closingTime": "2018-07-28T23:59:59+09:00",
    "type": "Closed"
  }
]
      ✓ should not error when fetching schedule (97ms)
      ✓ should have schedule data
      ✓ should have a valid date for each schedule entry
      ✓ should have a valid opening time for each schedule entry
      ✓ should have a valid closing time for each schedule entry


  5 passing (327ms)
  9 failing

  1) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should not return an error fetching ride times:

      Uncaught AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(!err)

      + expected - actual

      -false
      +true
      
      at /root/park/node_modules/themeparks/lib/testonline.js:26:17
      at TokyoDisneyResortDisneySea.<anonymous> (node_modules/themeparks/lib/park.js:155:17)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)

  2) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have some ride data:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(times)

      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:32:13)

  3) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have an ID for every ride:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:41:42)

  4) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have a wait time for every ride:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:45:42)

  5) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have a name for every ride:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:49:42)

  6) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have an active state for every ride:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:53:42)

  7) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have a fastpass field for every ride:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:57:42)

  8) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have a status field for every ride:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:68:42)

  9) Park TokyoDisneyResortDisneySea
       Get Park Wait Times
         should have matching status and active fields:
     TypeError: Cannot read property '0' of undefined
      at Context.<anonymous> (node_modules/themeparks/lib/testonline.js:79:42)



`

**Comment by nppi3enz** [comment]
It works
I have deleted and re-created the server.
Thanks for the great support.
