### ISSUE TITLE
Some Asterix coasters are closed and/or contain "??" name

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#116]
Hello there !
A new issue with the Asterix's api.
Some coasters are always closed, and for some coasters, the name are "??", how to fix it ?

Cordially,
Louis FORAUX

**Comment by cubehouse** [comment]
Do you know if these coasters are the newest one? Somebody may need to update the AsterixData.js file in the library.

**Comment by LouisForaux** [comment]
Is not a new coaster...
I'll look on a few days, I'll post here the result
