### ISSUE TITLE
Add "Bellewaerde Park"

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#117]
Hello !
Can you add Bellewaerde Park in the API ?
There is the Realtime Wait times API : http://bellewaer.de/realtime/api/api-realtime.php
There is the Attraction List : https://pastebin.com/m1Z6KJX5

Cordially,
Louis

**Comment by LouisForaux** [comment]
Hey !
Have you some news about this add to your api ?

Cordially,
Louis

**Comment by cubehouse** [comment]
Hi,

I'm not planning on adding this to the library myself any time soon as I have other priories to work on within the library and my time is very limited!
But please feel free to add it yourself with a pull request.

**Comment by LouisForaux** [comment]
But, i don't know how it's work for add a new park....

**Comment by cubehouse** [comment]
I may get the chance to add it sometime in the future, but when I'm asked to add a new park, I'm also being asked to monitor and maintain that implementation for the foreseeable future, which is a lot of time for me to dedicate where it already takes a fair amount of my time to maintain the existing parks.

There is a rough park on the wiki for how to add new parks, and I recommend looking at maybe Efteling or some of the other simpler parks to get an idea of how they're built. A lot of the code is fairly clean, so should serve as a good introduction to adding more parks.

Hope this helps!

**Comment by jeanmatthieud** [comment]
I think that this issue can be closed with PR #155
