### ISSUE TITLE
Add liseberg park

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#118]
good evening, 
There is the Realtime Wait times And ride name page : https://www.liseberg.com/rides-attractions/
and opening time : https://www.liseberg.com/opening-times/

https://www.liseberg.com/en/api/queue/87
https://www.liseberg.com/en/api/queue/89

=)

**Comment by elstringer** [comment]
```
openingHoursEndpoint: "/en/api/opening-hours/",
datePickerTranslationsEndpoint: "/en/api/datepicker/translations/",
jetshopApiBaseUrl: "https://kassa.liseberg.se/webapi/liseberg/",
jetshopImageBaseUrl: "//kassa.liseberg.se",
jetshopCheckoutBaseUrl: "https://kassa.liseberg.se/externalcheckout.aspx?language=en&cartid="
getExtendedPoiInformation: "/en/api/map/extendedpoibyid/",
getRelevantPoisByPoiId: "/en/api/map/relevantpoisbyid/",
getRelevantPoisByFilters: "/en/api/map/poisbyfilters/",
getFilters: "/en/api/map/filters/"
```

**Comment by cubehouse** [comment]
Thanks for the request, happy to accept a pull request adding this if you could code this into the library.

**Comment by hemi1986** [comment]
Im currently implementing liseberg park. How should we handle the waittime if the api is returning something like this: 
`{
  "id": 89,
  "name": "Barnens paradis",
  "status": "Queue: 0-10 min, closing 22:00"
}`
parsing shouldnt be the problem but which number should we use? Minimum waittime, maximum waittime or something in between?

**Comment by cubehouse** [comment]
Weeeeeerrrrird. I'd go for the maximum if that is predictable.
