### ISSUE TITLE
Efteling park wait times broken

### ISSUE THREAD

**Issue by renssies** [cubehouse/themeparks#119]
It looks like Efteling switches APIs again, the current wait times API now returns a 403 "Forbidden". 

I'm looking into finding a new API, but it looks like the app now uses certificate pinning, so charles doesn't work

**Comment by cubehouse** [comment]
Indeed, it is now using certificate pinning!

Looks like the API completely moved to https://api.efteling.com/app/wsi as well.

**Comment by renssies** [comment]
Hmm ok, so now we need to find out which header it needs for the authentication token to be valid.

**Comment by cubehouse** [comment]
OK, figured it out.
https://gist.github.com/cubehouse/65f7e12dd62eae75e8e3a1a753b18c2d

Will publish new version on npm when I get a sec.

**Comment by renssies** [comment]
Thank you very much for finding a solution this quickly :)

**Comment by cubehouse** [comment]
No problem!
Fixed in 4.7.2, just uploaded it

**Comment by renssies** [comment]
Last question, how did you find the API key? I was searching through the APK, but I didn't find this one. Only an obfuscated API key, which I couldn't find how to decode.

**Comment by cubehouse** [comment]
The prd-search-acs.efteling.com request is using the same API key, but without certificate pinning ;)

**Comment by renssies** [comment]
Ah, I didn't see it because they only use an API key for that call on Android, not on iOS

**Comment by cubehouse** [comment]
Great. I'm going to delete the last few comments FYI just to clean up and try not to encourage a cat-and-mouse between us and Efteling...

Thank you for reporting the issue!
