### ISSUE TITLE
TokyoDisneyResortMagicKingdom & TokyoDisneyResortDisneySea error invalidVersion

### ISSUE THREAD

**Issue by nppi3enz** [cubehouse/themeparks#121]
Error fetching park opening times: 400: {
  "errors": [
    {
      "code": "error.invalidVersion"
    }
  ]
}
Error fetching park wait times: 400: {
  "errors": [
    {
      "code": "error.invalidVersion"
    }
  ]
}

======================================
// include the Themeparks library
var Themeparks = require("themeparks");

// access a specific park
var park = new Themeparks.Parks.TokyoDisneyResortMagicKingdom();

// access wait times by Promise
park.GetWaitTimes().then(function(rides) {
    // print each wait time
    for(var i=0, ride; ride=rides[i++];) {
        console.log(ride.name + ": " + ride.waitTime + " minutes wait");
    }
}, console.error);

// get park opening times
park.GetOpeningTimes().then(function(times) {
    // print opening times
    for(var i=0, time; time=times[i++];) {
        if (time.type == "Operating") {
            console.log("[" + time.date + "] Open from " + time.openingTime + " until " + time.closingTime);
        }
    }
}, console.error);

**Comment by cubehouse** [comment]
Looks like they've bumped their app version.

I'll update the library later today. For now, pass in this to your constructor and it will work again. 
{
"api_version": "1.0.2"
}

**Comment by cubehouse** [comment]
Fix published in 4.7.4
