### ISSUE TITLE
Disney Tokyo version borked again 

### ISSUE THREAD

**Issue by dotaguro** [cubehouse/themeparks#122]
Error fetching park opening times: 400: {
"errors": [
{
"code": "error.invalidVersion"
}
]
}
Error fetching park wait times: 400: {
"errors": [
{
"code": "error.invalidVersion"
}
]
}

Needs to be bumped to 1.0.3.

**Comment by cubehouse** [comment]
Thanks for the report, PR #123 merged and published.

I'll try and find a more future-proof way of handling this when I get a moment. They are deprecating their API versions phenomenally fast, most users not auto-updating in the app stores are going to have a very poor experience.
