### ISSUE TITLE
Not getting any data from Disney Parks

### ISSUE THREAD

**Issue by zpocbob** [cubehouse/themeparks#132]
Disney World and Disneyland parks are not pulling data.  It looks like it quit sometime in the last few days.

**Comment by cubehouse** [comment]
Thanks for you report.

What version of the library are you using, and are there any errors?

**Comment by PhilippeP62** [comment]
Same thing for Disneyland Paris, they updated their website around Octobre
24 to match US parks websites.

I still used an old version of wdwjs (yes I Know) , busy upgrading to the
latest.

Philippe

**Comment by cubehouse** [comment]
Running against 4.7.8 using:

```PRINTDATA=true PARKID=WaltDisneyWorldMagicKingdom NODE_DEBUG=themeparks npm run testonline```
and
```PRINTDATA=true PARKID=DisneylandParisMagicKingdom NODE_DEBUG=themeparks npm run testonline```

Seems to be behaving as expected for me.

wdwjs was deprecated around 2 years ago (!), so I would strongly recommend updating to a more recent version.

**Comment by PhilippeP62** [comment]
I know  for wdwJS , but as long as it worked ...
Upgraded to themeparks 4.7.9 , and waittimes jsons are coming down again ,
so it's ok for me

Philippe

Le sam. 3 nov. 2018 à 13:39, Jamie Holding <notifications@github.com> a
écrit :

**Comment by cubehouse** [comment]
I've not heard anything back from @zpocbob in just over a week, so I am going to close this.
