### ISSUE TITLE
5.0 - Refurbishment isn't implanted

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#135]
**Park**
Which park/resort has this issue?
All
**Context**
- themeparks version used: 5.0
- Operating System: All

**Describe the bug**
Hello there ! The 'Refurbishment' status doesn't exists in the 5.0. This feature was very appreciated by our users. 

**Output**
Closed and not Refurbishment in concerned rides.

Cordially,
Louis

**Comment by cubehouse** [comment]
Thank you for the report, I will look into this.

**Comment by cubehouse** [comment]
Hi,

This appears to have been implemented already for Efteling, but was missing from Disney parks as their API has changed significantly recently and it was missed.

Were there any other parks you were specifically expecting this to exist in before, but now isn't?

**Comment by LouisForaux** [comment]
Hi!
Oh okay!
I haven't seen in other parks before. I'll look this in a few days. Maybe it's user by Europapark?

I'll add new parks in my android App in a few days :)

**Comment by cubehouse** [comment]
Looking through the code, I don't think we've ever supported refurbishment status for EuropaPark.

**Comment by LouisForaux** [comment]
Okay

In the Beta 8, in my tests, the schedule opening has not shawn in Disney parks and maybe others, you have an answer for me?

**Comment by cubehouse** [comment]
Sorry, I'm afraid I don't understand your query.

**Comment by cubehouse** [comment]
This has been dormant for a while now, so I am closing.
