### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by matounet51** [cubehouse/themeparks#139]
Hi!

I'm a french user, so... sorry for my bad english!

I use your library for my own app and site. You can see the site [here - D-land.fr](http://d-land.fr) and the App on Google Playstore (App name is Dland).

For the app, I have a problem... How can I use the library to integrate waits directly in android? 
My app use webview to my website...

**Comment by cubehouse** [comment]
Thank you @tpxtron for the reply. What you say is pretty bang on correct.

You need to have a web server running somewhere that will fetch updated data at regular intervals (say, 10 minutes) and store these locally (in memory, a redis store, SQL, whatever takes your fancy).
Then build an basic API that returns the last stored value when called so your website and app can display them.

You may find that the JSON object the library returns is already all you need and you can save/return that as it is, but I suspect you'll want to massage it into your own data format that will suit your application better.

Personally, I have a private app I use myself for my vacations that does a bunch of compression and binary diffing on the data (to try and cope with the poor roaming network conditions), injects things like park temperature and other potentially useful information. You want this to always run and digest information over time. You don't want to make requests to the library every single time your API is called, as if you get a lot of users, you'll be making an awful lot of wasted requests that will slow down your application.
