### ISSUE TITLE
Disney Tokyo version borked again

### ISSUE THREAD

**Issue by nicectrl** [cubehouse/themeparks#142]
Error fetching park wait times: 400: {
  "errors": [
    {
      "code": "error.invalidVersion"
    }
  ]
}

**Comment by nicectrl** [comment]
what's the name of tokoy disney app?

**Comment by cubehouse** [comment]
Tokyo Disney app is jp.tokyodisneyresort.portalapp

It's not available on international Google Play Stores.

**Comment by cubehouse** [comment]
Fixed and will be pushed live in 4.7.12 shortly

**Comment by nicectrl** [comment]
thank you
