### ISSUE TITLE
DisneylandParisMagicKingdom: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by VitalyChe** [cubehouse/themeparks#144]
Could you, please, check the issue

NODE_DEBUG=themeparks PARKID=DisneylandParisMagicKingdom npm run testonline

`(node:13154) UnhandledPromiseRejectionWarning: 503: {
  "errors": [
    {
      "typeId": "SERVICE_CALL_ERROR",
      "message": "Error calling Facility Service.",
      "systemErrorCode": "220038"
    }
  ]
}`

**Comment by matounet51** [comment]
I have the same issue for DisneylandParisMagicKingdom and for DisneylandParisWaltDisneyStudios...

**Comment by tquentin38** [comment]
Same issue here ....
```
(node:1401) UnhandledPromiseRejectionWarning: 503: {
  "errors": [
    {
      "typeId": "SERVICE_CALL_ERROR",
      "message": "Error calling Facility Service.",
      "systemErrorCode": "220038"
    }
  ]
}
(node:1401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LouisForaux** [comment]
Is the same here, after a downtime at Disneyland Paris of her servers.....

Probably a change about an endpoint ?

**Comment by VitalyChe** [comment]
The fix has been proposed!
