### ISSUE TITLE
Tokyo Disney Resort fails

### ISSUE THREAD

**Issue by SomethingWithComputers** [cubehouse/themeparks#146]
**Park**
Tokyo Disney Resort (both sea and world)

**Context**
- themeparks version used: 4.17.13
- Operating System: MacOS Mojave and Ubuntu 18.04 LTS

**Describe the bug**

**Output**
When trying to fetch the waiting times for Tokyo Disney Sea or World, this is always the response:
```
Error fetching park wait times: 401: {
  "errors": [
    {
      "code": "error.invalid",
      "property": "deviceId"
    }
  ]
}
```

**Comment by cubehouse** [comment]
Hi,

Sorry but I can't reproduce this issue. I am running the following with success:

PRINTDATA=true NODE_DEBUG=themeparks PARKID=TokyoDisneyResortMagicKingdom npm run testonline

**Comment by dotaguro** [comment]
Works for me too, fwiw

**Comment by SomethingWithComputers** [comment]
I've only been able to reproduce it on my server, my local version mostly works fine. It seems that the `s_deviceID` is not set before the call to the API is made when utilising the FetchWaitTimes method. I've solved the issue for now by explicitly adding a call that sets the `s_deviceID` before fetching the rest of the wait times as such (in Tokyo Disney's index.js file):
```
        ...
        key: "FetchWaitTimes",
        value: function FetchWaitTimes() {
            var _this4 = this;

            // first get our ride names etc.
            return this.FetchDeviceID().then(function (deviceId) {
                _this4[s_deviceID] = deviceId;
                return _this4.FetchRideData().then(function (rides) {
        ...
```
I make two call sequentially to both parks in the Tokyo Disney Resort and whichever resort is called second has this bug. I do know my server is running a different version of Node, but I'll check when I get home which one specifically.

**Comment by cubehouse** [comment]
Thanks for the update, it looks like device ID may be generated separately between parks now.

This should be the fix:
```@@ -109,11 +109,11 @@ class DisneyTokyoPark extends Park {
     }
 
     FetchDeviceID() {
         if (this[s_deviceID]) return Promise.resolve(this[s_deviceID]);
 
-        return this.Cache.WrapGlobal("tdrDeviceID", () => {
+        return this.Cache.Wrap("tdrDeviceID", () => {
             return this.HTTP({
                 url: `${this[s_apiBase]}/rest/v1/devices`,
                 method: "POST",
                 headers: this.GetAPIHeaders(),
             }).then((data) => {
```

I'll do some testing and push out a fix if this resolve this.

**Comment by SomethingWithComputers** [comment]
Great news! Thanks!

**Comment by cubehouse** [comment]
Pushed out 4.7.14. Let me know if that does or doesn't work :)
