### ISSUE TITLE
Europapark error

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#153]
**Park**
Which park/resort has this issue?
Europapark

**Context**
- themeparks version used: 4.8.0
- Operating System: Ubuntu 18 on Heroku

**Describe the bug**
On the API 5.9 by Europapark : 
`{
  "code": 500,
  "type": "unknown",
  "message": "java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $"
}`
[API 5.9](https://api.europapark.de/api-5.9/pointsofinterest)

**How to correct**
Use the version 5.6 instead of 5.9 >> It's Working by open the url in browser.
I can't change the api version and test...
[API 5.6](https://api.europapark.de/api-5.6/pointsofinterest)

Cordially,
Louis

**Comment by jeanmatthieud** [comment]
This issue can be closed as the API park is working again
