### ISSUE TITLE
Disneyland Paris Opening Times

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#182]
**Park**
Disneyland Paris (MK/WDS)

**Context**
- themeparks version used: 5.1.4
- Operating System: Mac OS x

**Describe the bug**
Not the right opening times are showed.

**Output**

{

"date": "2019-06-15",

"openingTime": "2019-06-15T12:00:00+02:00",

"closingTime": "2019-06-16T01:00:00+02:00",

"type": "Operating",

"special": [

{

"openingTime": "TZ|2019-06-15T06:30:00.000Z|Europe/Paris",

"closingTime": "TZ|2019-06-15T07:30:00.000Z|Europe/Paris",

"type": "Extra Magic Hours"

},

{

"openingTime": "TZ|2019-06-14T06:30:00.000Z|Europe/Paris",

"closingTime": "TZ|2019-06-14T07:30:00.000Z|Europe/Paris",

"type": "Extra Magic Hours"

},

{

"openingTime": "TZ|2019-06-14T08:30:00.000Z|Europe/Paris",

"closingTime": "TZ|2019-06-14T09:30:00.000Z|Europe/Paris",

"type": "Extra Magic Hours"

},

{

"openingTime": "TZ|2019-06-15T08:30:00.000Z|Europe/Paris",

"closingTime": "TZ|2019-06-15T09:30:00.000Z|Europe/Paris",

"type": "Extra Magic Hours"

}

]

},

Many different times for Extra Magical Hours (2 was not the right hours) and the opening times are 12h to 1h

**Comment by LouisForaux** [comment]
After checking, is a Timezone mistake. The timezone was added at the informations gived by Disneyland Paris. Normal Operating Hours : 10h to 23h. Timezone +2 : 12h to 1h.
At this time, no explications for the wrong EMH.

**Comment by cubehouse** [comment]
This looks like the "special" schedule times are being returned in the wrong format (that looks like the internal Moment caching format I'm using).

**Comment by cubehouse** [comment]
Looking at this closer, those times aren't right, they're

**Comment by cubehouse** [comment]
Should be fixed with 197d70139681312e46c809751c3b347fcd845ebd.

Will be rolled out to npm in a while in 5.1.5
