### ISSUE TITLE
Dependency and loader issues 

### ISSUE THREAD

**Issue by agray5** [cubehouse/themeparks#191]
**Park**
Which park/resort has this issue?
N/A

**Context**
- themeparks version used: 5.1.7
- Operating System: Linux Mint 18.3 

How to find your themeparks version:
Linux: npm list --depth=0 | grep themeparks
Windows CMD: npm list | find "themeparks"
PowerShell: npm list | sls themeparks

**Describe the bug**
After installing via npm and requiring the library in the project, there is a lot of dependencies missing. 
This is what appears in the terminal: 
![image](https://user-images.githubusercontent.com/25891362/59970565-fe5c3200-952e-11e9-8dfb-17ab2ee07ea6.png)

Even after manually installing the dependencies webpack warns of dependencies as expressions:
![image](https://user-images.githubusercontent.com/25891362/59970581-893d2c80-952f-11e9-99c6-63c8221ea272.png)

It also warns about missing loaders:
![image](https://user-images.githubusercontent.com/25891362/59970583-b25dbd00-952f-11e9-8ff9-c335c5c35644.png)

**Output**
Sample output with NODE_DEBUG=themeparks environment variable set.
Eg. if this is an issue with a specific park, run the following to run an online test of that park with debugging enabled:
PARKID=WaltDisneyWorldMagicKingdom NODE_DEBUG=themeparks PRINTDATA=true npm run testonline

No addition output with environment variable.

I would really like to use this, but I cannot figure out how to get it to work.

**Comment by cubehouse** [comment]
Are you trying to include this in a frontend? That is my guess from your screenshots trying to webpack a server-side library.

This library only work with NodeJS, and is not designed for web/app clients.
