### ISSUE TITLE
lastUpdate not updated when fastpass return times change but wait time remains the same

### ISSUE THREAD

**Issue by webdeck** [cubehouse/themeparks#195]
**Park**
Disney

**Context**
- themeparks version used: 5.1.7
- Operating System: macos 10.14

**Describe the bug**
When the fastpass return times change, but the wait time remains the same as the previous poll, the lastUpdate time is not updated.

**Output**
n/a

**Comment by cubehouse** [comment]
Pushed live in 5.1.8
