### ISSUE TITLE
Add information on Star Wars Galaxy's Edge boarding groups for Disneyland

### ISSUE THREAD

**Issue by webdeck** [cubehouse/themeparks#199]
**Is your feature request related to a problem? Please describe.**
Currently, information is returned on whether the Star Wars Galaxy's Edge ride object is open or closed.  Closed seems to indicate that a boarding group is required.

**Describe the solution you'd like**
Provide details on which boarding groups are being distributed and which boarding groups are allowed access to the land.  Can be similar to how fastpass is handled via meta data.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by cubehouse** [comment]
Is this information available within the app? If you know how it is presented I may be able to look into it.

Or if you know and can submit a pull request, it would be greatly appreciated.

**Comment by webdeck** [comment]
You can see a number of screen shots in this Facebook post that show what it looks like in the app.  The app gets a push notification when your boarding group is called and then the app shows your boarding pass. Not sure how to see what boarding groups are currently being let into the land though, but it is shown on digital signs in the park. Also if you don’t have a boarding pass, the app gives a rough estimate (eg early afternoon) for when your group will be called. 

https://m.facebook.com/DisneylandDailyCasey/photos/pcb.2154031601361138/2154031518027813/?type=3&source=48

**Comment by webdeck** [comment]
More information here, showing that boarding group times are also available:  https://touringplans.com/blog/2019/06/25/galaxys-edge-general-opening-recap/

**Comment by cubehouse** [comment]
I did look into this briefly. The page uses a completely different API for Galaxy's Edge entry specifically.

Do we know how long this system will be active?

**Comment by webdeck** [comment]
They haven’t announced an end date, but I expect them to keep it in place until after Rise of the Resistance opens later this year since that would drive another surge in traffic.

**Comment by thomasstoeckert** [comment]
I wouldn't consider these important at all - Disneyland hasn't used boarding groups since the second day of regular operation, and the same appears to have occurred in WDW.

**Comment by cubehouse** [comment]
I think this is too bespoke and under utilised to be considered for this library. Thank you for your suggestion though :)
