### ISSUE TITLE
API Library Frequent 401s

### ISSUE THREAD

**Issue by travisrl** [cubehouse/themeparks#208]
**Park**
All parks

**Context**
- themeparks version used: latest
- Operating System: Ubuntu 18.10

**Describe the bug**
API library returns 401 throughout the day disabling an app using it to fetch park or attraction data. Appears to happen at least once a day for extended periods of time. 

Hoping this is something resolvable on the library side as it happens frequently independent of machine or application (from basic app to more complicated.)

**Output**
This is the response that the API gives: Error 401: {
```
app_1 | [1] "type": "Buffer",
app_1 | [1] "data": []
app_1 | [1] }
```

**Comment by TheConsciousness** [comment]
@travisrl How did you resolve this issue?
