### ISSUE TITLE
CacheWaitTimesLength not working in 5.0

### ISSUE THREAD

**Issue by jtmaddux** [cubehouse/themeparks#209]
I am having trouble getting CacheWaitTimesLength to have any impact.  I seem to get 5min wait even when I program a different value, for example:

var Themeparks = require("themeparks");
Themeparks.Settings.CacheWaitTimesLength = 60; //Time to cache waiting times (in seconds)

**Comment by jtmaddux** [comment]
I've had more success with this syntax:
var disneyland = new Themeparks.Parks.DisneylandResortMagicKingdom({'cacheWaitTimesLength':  1});

**Comment by cubehouse** [comment]
Themeparks.Settings.CacheWaitTimesLength is no longer used.

I need to update the documentation, it's a little out-of-date following some rush jobs getting 5.x out when the old Disney API changed.
