### ISSUE TITLE
Opening Hours Not Updating

### ISSUE THREAD

**Issue by trwarren** [cubehouse/themeparks#210]
The GetOpeningTimes function seems to be returning old data even though the request is made after the configured cache wait time has passed. 

For example, several hours after first requesting the opening times, on re-issuing the request I get this data:

{ date: '2019-07-25',
  openingTime: '2019-07-25T23:59:59-07:00',
  closingTime: '2019-07-25T23:59:59-07:00',
  type: 'Closed' }

(and the park is in fact open at this time). If I delete the sqlite db file and rerun, then it reports correctly:

{ date: '2019-07-25',
  openingTime: '2019-07-25T08:00:00-07:00',
  closingTime: '2019-07-26T00:00:00-07:00',
  type: 'Operating',
  special:
   [ { openingTime: '2019-07-25T07:00:00-07:00',
       closingTime: '2019-07-25T08:00:00-07:00',
       type: 'Extra Magic Hour and Magic Morning' } ] }

so seems to be a cache problem?

Also, I don't fully understand why the park hours would be reported as 23:59:59 when it is closed even though later in this day it will be operating.

**Comment by trwarren** [comment]
The GetOpeningTimes function seems to be returning old data even though the request is made after the configured cache wait time has passed. 

For example, several hours after requesting the opening times I get this data:

{ date: '2019-07-25',
  openingTime: '2019-07-25T23:59:59-07:00',
  closingTime: '2019-07-25T23:59:59-07:00',
  type: 'Closed' }

(and the park is in fact open at this time). If I delete the sqlite db file and rerun, then it reports correctly:

{ date: '2019-07-25',
  openingTime: '2019-07-25T08:00:00-07:00',
  closingTime: '2019-07-26T00:00:00-07:00',
  type: 'Operating',
  special:
   [ { openingTime: '2019-07-25T07:00:00-07:00',
       closingTime: '2019-07-25T08:00:00-07:00',
       type: 'Extra Magic Hour and Magic Morning' } ] }

so seems to be a cache problem?

Also, I don't fully understand why the park hours would be reported as 23:59:59 when it is closed even though later in this day it will be operating.

**Comment by gberg927** [comment]
This was happening to me too, but seems to have resolved itself.
