### ISSUE TITLE
Add Legoland Germany

### ISSUE THREAD

**Issue by ghost** [cubehouse/themeparks#220]
**Park Name**
Legoland Germany

**Park Android/iOS/Web Apps**
https://itunes.apple.com/de/app/legoland-deutschland-resort/id1389753425?ls=1&mt=8
https://play.google.com/store/apps/details?id=biz.merlinentertainments.legoland.deutschland

**Additional Information**
Waiting times are only available within the park. Apparently the waiting times are also available via "api.attractions.io/v1/" from Merlin Parks.

**Comment by cmenkemeller** [comment]
@cubehouse I saw you added this park recently. Can this be closed?
