### ISSUE TITLE
FerrariLand : Waiting Time Error

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#228]
**Park**
FerrariLand

**Context**
- themeparks version used: 5.1.14

**Describe the bug**
The wait times of Ferrari Land are no longer updated the values ​​are empty

**Output**

`[{"meta":{"longitude":1.15278,"latitude":41.084,"area":"Ferrari Land"},"id":"FerrariLand_320","name":"Red Force","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.456Z","status":"Operating"},{"meta":{"longitude":1.150471,"latitude":41.085006,"area":"Ferrari Land"},"id":"FerrariLand_328","name":"Torre de caída Libre","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.456Z","status":"Operating"},{"meta":{"longitude":1.150626,"latitude":41.085013,"area":"Ferrari Land"},"id":"FerrariLand_329","name":"Torres de rebote","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.456Z","status":"Operating"},{"meta":{"longitude":1.151356,"latitude":41.085035,"area":"Ferrari Land"},"id":"FerrariLand_346","name":"Maranello Grand Race","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.152485,"latitude":41.084986,"area":"Ferrari Land"},"id":"FerrariLand_347","name":"Racing Legends","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.152285,"latitude":41.084982,"area":"Ferrari Land"},"id":"FerrariLand_348","name":"Flying Dreams","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.152818,"latitude":41.084784,"area":"Ferrari Land"},"id":"FerrariLand_349","name":"Junior Championship","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.152786,"latitude":41.085158,"area":"Ferrari Land"},"id":"FerrariLand_350","name":"Kid's Podium","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.152718,"latitude":41.084912,"area":"Ferrari Land"},"id":"FerrariLand_351","name":"Pole Position Challenge","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.151979,"latitude":41.08433,"area":"Ferrari Land"},"id":"FerrariLand_326","name":"Pit Stop Record","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.1501,"latitude":41.0839,"area":"Ferrari Land"},"id":"FerrariLand_485","name":"Crazy Pistons","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.1505,"latitude":41.0841,"area":"Ferrari Land"},"id":"FerrariLand_487","name":"Junior Red Force","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.151,"latitude":41.0837,"area":"Ferrari Land"},"id":"FerrariLand_484","name":"Kids’ Tower","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.1513,"latitude":41.0839,"area":"Ferrari Land"},"id":"FerrariLand_483","name":"Champions Race","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"},{"meta":{"longitude":1.15123,"latitude":41.0836,"area":"Ferrari Land"},"id":"FerrariLand_486","name":"Flying Race","active":true,"waitTime":null,"fastPass":false,"lastUpdate":"2019-09-08T15:04:44.457Z","status":"Operating"}]`

**Comment by cubehouse** [comment]
Ferrari land does not return full wait times in the app, we return as much data as we can get (ride names, status, locations). Null signifies that the park has chosen to not supply wait times for this ride, so this is (as far as I am concerned) correct.

Please update and re-open if you find the app is supplying wait times, and you can supply a pull request accessing them.
