### ISSUE TITLE
DisneylandParis & Studio : Refurbishment Error

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#229]
**Park**
DisneylandParisMagicKingdom
DisneylandParisWaltDisneyStudios

**Context**
- themeparks version used: 5.1.14

**Describe the bug**
the attractions in Refurbishment are considered closed by the script

**Currently there are some attractions in refurbishment**

- Walt disney Studio:
Rock 'n' Roller Coaster avec Aerosmith
Cars Quatre Roues Rallye
Art of disney Animation

- DisneylandParis:
Indiana Jones™ et le Temple du Péril
Autopia
Les mysteres du nautilus
it's a small world
Disney Railroad

**Output**

`[{"meta":{"longitude":2.778767,"latitude":48.866753,"photoPass":true},"id":"DisneylandParisWaltDisneyStudios_P2ZA02","name":"The Twilight Zone Tower of Terror™","active":true,"waitTime":40,"fastPass":true,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"},{"meta":{"longitude":2.776959,"latitude":48.867136},"id":"DisneylandParisWaltDisneyStudios_P2XA08","name":"Slinky Dog Zigzag Spin","active":true,"waitTime":10,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"},{"meta":{"longitude":2.777902,"latitude":48.866697},"id":"DisneylandParisWaltDisneyStudios_P2XA00","name":"Studio Tram Tour : Behind the Magic","active":false,"waitTime":0,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Closed"},{"meta":{"singleRider":true,"longitude":2.776651,"latitude":48.866903},"id":"DisneylandParisWaltDisneyStudios_P2XA06","name":"RC Racer","active":true,"waitTime":50,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"},{"meta":{"longitude":2.777854,"latitude":48.867726},"id":"DisneylandParisWaltDisneyStudios_P2XA02","name":"Cars Quatre Roues Rallye","active":false,"waitTime":0,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Closed"},{"meta":{"longitude":2.779271,"latitude":48.865195,"photoPass":true},"id":"DisneylandParisWaltDisneyStudios_P2ZA01","name":"Rock 'n' Roller Coaster avec Aerosmith","active":false,"waitTime":0,"fastPass":true,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Closed"},{"meta":{},"id":"DisneylandParisWaltDisneyStudios_P2XA01","name":"Art of Disney Animation","active":false,"waitTime":0,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Closed"},{"meta":{"singleRider":true,"longitude":2.778142,"latitude":48.868041},"id":"DisneylandParisWaltDisneyStudios_P2XA03","name":"Crush's Coaster","active":true,"waitTime":70,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"},{"meta":{"singleRider":true,"longitude":2.7762224525213237,"latitude":48.86757046243673},"id":"DisneylandParisWaltDisneyStudios_P2XA09","name":"Ratatouille : L'Aventure Totalement Toquée de Rémy","active":true,"waitTime":30,"fastPass":true,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"},{"meta":{"longitude":2.778352,"latitude":48.868288},"id":"DisneylandParisWaltDisneyStudios_P2XA05","name":"Les Tapis Volants – Flying Carpets Over Agrabah","active":true,"waitTime":15,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"},{"meta":{"singleRider":true,"longitude":2.777234,"latitude":48.867188},"id":"DisneylandParisWaltDisneyStudios_P2XA07","name":"Toy Soldiers Parachute Drop","active":true,"waitTime":45,"fastPass":false,"lastUpdate":"2019-09-08T15:04:48.590Z","status":"Operating"}]`

**Comment by cubehouse** [comment]
I believe Rock 'n' Roller Coaster avec Aerosmith, and Art of Animation are both closed, and these will return as new attractions?

**Comment by LouisForaux** [comment]
Hey,

Rock'n'roller coaster will reopen later yes

And Art Of Disney Animation are now Art of Celebration (in memory) and
reopen soon

Yes any rides are in Refurbishment and not closed (Like Small World or
Indiana Jones)

Amicaly,
Louis

**Comment by cubehouse** [comment]
Not going to look into this myself now as I have too much on my plate. Will happily review any pull requests though.

**Comment by cubehouse** [comment]
Everything seems fine in 5.1.28 to me.

Please offer a pull request with the expected result if this is still happening.

Thanks!
