### ISSUE TITLE
Missing WDW Resorts

### ISSUE THREAD

**Issue by gberg927** [cubehouse/themeparks#230]
Hi,

Not totally sure where the list of disneyFacilities couchlite db is actually coming from, but I am only getting a few resorts listed. 

- Walt Disney World Swan Hotel
- The Cabins at Disney's Fort Wilderness Resort
- The Campsites at Disney's Fort Wilderness Resort
- Disney's Saratoga Springs Resort & Spa

Is this accurate? If so, is the possibility of more resorts coming?

Thanks,
Dennis

**Comment by cubehouse** [comment]
The library only fetches the data it believes it needs into the database (and often more than it really needs, but plays it safe).

Anything outside of the API methods listed isn't supported by the library I'm afraid. Please feel free to investigate the couchbase database syncing and setup something yourself if you wish to have this information, but generally having this data is outside of the scope of this project at the moment.
