### ISSUE TITLE
Disneyland Paris Ride Opening time bad format

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#241]
**Park**
Disneyland Paris (MK & WDS)

**Context**
- themeparks version used: 5.1.21
- Operating System: macOS

**Describe the bug**
The rides opening times are in this format : "08:30:00" and not in MomentJS Format 

**Output**
`meta:
openingTime : "08:30:00"
closingTime : "19:00:00"`

**Comment by cubehouse** [comment]
Meta data is much "looser" than other data, it's optional and will be in various formats for any park (or not exist at all).
If it would be better as a Moment object, please feel free to pull request it.

**Comment by LouisForaux** [comment]
I've made the #242 pull request ;)

**Comment by cubehouse** [comment]
Paris now returns meta like this:

```
    "meta": {
        "rideOpeningTime": "2019-10-19T08:27:00+02:00",
        "rideClosingTime": "2019-10-19T20:00:00+02:00",
        "singleRider": true,
        "singleRiderWaitTime": 30
    }
```

Hope that works and is formatted better now!
