### ISSUE TITLE
Disneyland Paris - FastPass null

### ISSUE THREAD

**Issue by LouisForaux** [cubehouse/themeparks#254]
**Park**
Disneyland Paris - MK and WDS

**Context**
- themeparks version used: 5.1.28
- Operating System: Heroku

**Describe the bug**
The FastPass section return false, even if the ride have FastPass System
**Output**
```fastPass : false```

**Comment by cubehouse** [comment]
We haven't supported fastpass for DLP for a while (if you call .FastPass on the object it will return false to indicate we don't know about DLP fastpass status).

But I have now added support by querying the app's updated API.
