### ISSUE TITLE
Disneyland Paris crash since today

### ISSUE THREAD

**Issue by PhilippeP62** [cubehouse/themeparks#255]
**Park**
Which park/resort has this issue?

**Context**
- themeparks version used: 5.1.21
- Operating System: raspbian

**Describe the bug**
Retrieving waittimes crashes since this morning ...(changes nothing)
I'll complete the info when I am not on my phone.
**Output**
                                                          
(node:9150) UnhandledPromiseRejectionWarning: 500: 500                    
(node:9150) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
 This error originated either by throwing inside of an async function with
out a catch block, or by rejecting a promise which was not handled with .c
atch(). (rejection id: 1)                                                 
(node:9150) [DEP0018] DeprecationWarning: Unhandled promise rejections are
 deprecated. In the future, promise rejections that are not handled will t
erminate the Node.js process with a non-zero exit code.

**Comment by cubehouse** [comment]
Looks like the official app is doing the same thing. Need to handle this error more gracefully

**Comment by PhilippeP62** [comment]
Well as for some reason , I couldn't run 'npm run testonline' , I upgraded
to the latest nodejs/npm and some other things are broken now :/

It's halloween 😁 I'll go back to this tomorrow ...

The official app seemed to work...


Le jeu. 31 oct. 2019 à 11:19, Jamie Holding <notifications@github.com> a
écrit :

**Comment by zacharyedwardbull** [comment]
The API and app seems to be working again now, I found the official app wasn't working for most of this morning/afternoon.
