### ISSUE TITLE
Historical gathering

### ISSUE THREAD

**Issue by renatoreisnet** [cubehouse/themeparks#257]
**Is your feature request related to a problem? Please describe.**
No, but I'm currently developing an historical view and analysis over waitTimes data, from each park, and it would be nice if we could consult historically this data, instead of in real time

**Describe the solution you'd like**
Given a time range, return all registered waitTimes of attractions within a time interval.

**Describe alternatives you've considered**
I'm currently checking each 15 minutes to get and store the data from the Theme Parks I want

**Additional context**

**Comment by migo315** [comment]
Well, this is a library for fetching the current waiting times from the official api. I don't think there is any chance to get past waiting times. Your current alternative ...

>  I'm currently checking each 15 minutes to get and store the data from the Theme Parks I want

... should be the solution.

Another alternative would be to fetch the data from *Open Coaster Interface* - but not all parks from this library are currently available there. Anyway, take a look. Short example: For fetching the waiting times of Efteling at 11th November 14:00 and from Phantasialand at 13th October 12:45, the GraphQL request looks like this:

```
{
  efteling: park(id: "49f00560-9b8d-4c11-a3ed-f548192ef5d9") {
    name,
    waitingTimes(sort: MINUTES_DESC, timestamp: "2019-11-11 14:00") {
      name,
      minutes
    }
  },
  phantasialand: park(id: "f7328b4a-3308-4823-b4b6-58fb9a254199") {
    name,
    waitingTimes(sort: MINUTES_DESC, timestamp: "2019-10-13 12:45") {
      name,
      minutes
    }
  }
}
```

Test this request here ( https://oci.coaster.cloud/playground ). You can use the API without costs and without registration. Let me know if you are missing a park.

**Comment by cubehouse** [comment]
Hi!

I'm afraid this is beyond the scope of this project. Historical data is the property of the parks, so you are best to collect this yourself - or if somebody else is running a service that offers historical data, then you could use that.
