### ISSUE TITLE
Alton Towers Calendar API Changed

### ISSUE THREAD

**Issue by zacharyedwardbull** [cubehouse/themeparks#259]
**Park**
Alton Towers

**Describe the bug**
Alton Towers has updated it's calendar for the 2020 season, it no longer uses the old calendar API. The old calendar API (https://www.altontowers.com/Umbraco/Api/OpeningTimes/GetAllAttractionOpeningTimes) returns a 404.

The new calendar API is https://www.altontowers.com/umbraco/api/openinghours/getcalendar

This returns a response of the form
```
{
  "StartDate": "2019-11-23T00:00:00+00:00",
  "EndDate": "2020-11-08T00:00:00",
  "ClosedText": "Closed",
  "FirstDayOfWeekIsSunday": false,
  "Locations": [
    {
      "locationId": 2047,
      "locationName": "Theme Park",
      "days": [
        {
          "key": "20200321",
          "displayDate": "Saturday 21<sup>st</sup> March",
          "openingHours": "10am - 5pm",
          "lastEntryTime": "",
          "message": ""
        },
        ...
   },
   ...
  ]
}
```
This seems easier to parse compared to the old one.

**Comment by OkoWsc** [comment]
Now that's interesting they have a lastentry field, could this be merlin moving the RTP's onto one shared API?
That would make things a bit easier.

**Comment by cubehouse** [comment]
Thank you for reporting, I've updated the Alton Towers class to use this new URL.
