### ISSUE TITLE
Efteling Wait Times Issue

### ISSUE THREAD

**Issue by juliendogny** [cubehouse/themeparks#260]
**Park**
For Efteling on the WaitTimes request

**Context**
Latest version of the ThemePark Api

**Describe the bug**
For 2 days now, I've got a (504) Gateway Timeout return

Does anyone else have this issue ?
Tried with postman too and got the same issue
Maybe a change on the URL or an Efteling server issue

**Comment by thomasstoeckert** [comment]
I'm not encountering this issue on 5.1.28 - is there any difference between how themeparks functions in 28 and 29 for efteling?

**Comment by cubehouse** [comment]
No difference for Efteling https://github.com/cubehouse/themeparks/blob/master/CHANGELOG.md

Also looks like it is working for me :s

**Comment by juliendogny** [comment]
Hello,
Thanks for the quick replies.
Apparently, it's on the Eteling side. I got that issue until 9.50am this morning and it resolved when the park opened.
I'll continue to monitor and add a check for opening schedules to update wait times if needed
