### ISSUE TITLE
Tokyo Disney not work

### ISSUE THREAD

**Issue by nicectrl** [cubehouse/themeparks#267]
**Park**
Tokyo Disney

**Context**
- themeparks version used:lasted
- Operating System:linux

**Describe the bug**
APIVersion has updated to 1.1.6 .  But return bad html text.

**Output**
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html lang=\"ja\" xml:lang=\"ja\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n<meta http-equiv=\"content-language\" content=\"ja\" />\n<title>東京ディズニーリゾート・オフィシャルウェブサイト</title>\n<meta name=\"author\" content=\"(C)東京ディズニーリゾート\" />\n<meta name=\"description\" content=\"東京ディズニーリゾートでは、遊ぶこと、泊まること、食べること、ショッピング、すべてがエンターテイメント！東京ディズニーランド、東京ディズニーシーの2つのテーマパークを中心とした滞在型テーマリゾートです。\" />\n<meta name=\"keywords\" content=\"東京,ディズニーリゾート,ディズニーランド,ディズニーシー,TDR,TDL,TDS,テーマパーク,パレード,ショー,キャラクター\" />\n<meta name=\"title\" content=\"\" />\n<meta name=\"robots\" content=\"ALL\" />\n<meta name=\"copyright\" content=\"Disney All right reserved.\" />\n\n<meta http-equiv=\"content-style-type\" content=\"text/css\">\n<style type=\"text/css\">\nBODY {\n\tmin-width:950px;\n\tcolor:#333333;\n\tbackground: #FFFFFF;\n\tfont-size:10pt;\n\tmargin:0;\n\tpadding:0;\n\ttext-align:center;\n\tline-height:1.4;\n}\nUL, LI, P, DL, DT, DD {\n\tborder:none;\n\tlist-style:none;\n\tmargin:0;\n\tpadding:0;\n}\nH1, H2, H3, H4, H5, H6 {\n\tcolor:#002692;\n\tmargin:0 auto;\n\tborder:none;\n\tpadding: 0;\n}\nA:link {text-decoration:underline; color:#0033FF }\nA:visited {text-decoration:underline; color:#0033FF }\nA:active {text-decoration:underline; color:#0033FF }\nA:hover {text-decoration:underline; color:#FF00FF }\n\n#container {\n\tpadding-bottom:20px;\n}\n\n#header {\n\tclear:both;\n\twidth:950px;\n\tmargin:0 auto;\n\tpadding:20px 0;\n}\n#footer {\n\tclear:both;\n\tbackground:#358ce4;\n\twidth:950px;\n\tmargin:0 auto;\n\tpadding:8px 0;\n\tcolor:#ffffff;\n}\n#footer .copylight {\n\ttext-align:center;\n}\n\n#main {\n\t_zoom: 1;\n}\n\n#contents {\n\twidth:950px;\n\theight:auto !important;\n\tmin-height:650px;\n\t_height:650px;\n\tmargin:0 auto;\n\ttext-align:left;\n\t_zoom: 1;\n}\n#contents h1 {\n\tfont-size:20pt;\n\tfont-family: Arial Black, Gadget, sans-serif,\"HGPｺﾞｼｯｸE\",\"ＭＳ Ｐゴシック\",\"ＭＳ ゴシック\", Osaka;\n\tpadding:20px 0;\n\ttext-align:center;\n}\n</style>\n</head>\n\n<body onload=\"self.window.focus()\">\n<div id=\"container\">\n\n<div id=\"main\">\n\n<div id=\"contents\">\n<h1><font color=\"#ff0000\">東京ディズニーリゾートからのお知らせ</font></h1>\n<div><p style=\"text-align: center; \">東京ディズニーリゾート・オフィシャルウェブサイトは、現在アクセスできなくなっております。<br />\nしばらく時間をおいてから、再度アクセスしていただきますようお願いいたします。<br />\n<br />\nThis site is temporarily unavailable.<br />\nPlease try back again later.</p></div>\n</div>\n\n\n</div>\n\n\n<div id=\"footer\">\n<p class=\"copylight\">(c) Disney All right reserved.</p>\n</div>\n\n\n</div>\n</body>\n</html>"

**Comment by cubehouse** [comment]
It seems fine to me I'm afraid.

The HTML response you posted has "This site is temporarily unavailable.", which suggests their site was unavailable briefly, so I am going to close this since I don't think this is an issue?
