### ISSUE TITLE
Unable to update Dollywood opening time

### ISSUE THREAD

**Issue by jeanmatthieud** [cubehouse/themeparks#268]
**Park**
Dollywood

**Context**
- themeparks version used: 5.1.31
- Operating System: Linux

**Describe the bug**
Unable to update Dollywood opening time

**Output**
The log output of my app. 
I'm sorry I don't have the time now to launch the full update with the raw library.
```json
{"err":{"message":"scheduleData.forEach is not a function","name":"TypeError","stack":"TypeError: scheduleData.forEach is not a function\n    at FetchOpeningTimes.HTTP.then (node_modules/themeparks/lib/herschend/herschendparkbase.js:105:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}
```

**Comment by cubehouse** [comment]
I have pushed a fix through in 5.1.33 - let me know how it does.
