### ISSUE TITLE
Unable to update Phantasialand opening time

### ISSUE THREAD

**Issue by jeanmatthieud** [cubehouse/themeparks#269]
**Park**
Phantasialand 

**Context**
- themeparks version used: 5.1.31
- Operating System: linux

**Describe the bug**
Unable to update Phantasialand opening time

**Output**
Log ouput of my app.
I'm sorry I don't have the time now to get better logs.
```json
{"err":{"message":"Cannot read property 'replace' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'replace' of undefined\n    at calendarData.forEach (node_modules/themeparks/lib/phantasialand/phantasialand.js:140:50)\n    at Array.forEach (<anonymous>)\n    at FetchOpeningTimes.HTTP.then (node_modules/themeparks/lib/phantasialand/phantasialand.js:133:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}
```

**Comment by hemi1986** [comment]
Hi,

thanks for the bug report. I had a look at the "FetchOpeningTimes" method i recently updated at phantasialand because they changed their website and found the problem. I made a pull request which should fix that problem.
