### ISSUE TITLE
Tokyo Disneyland access from AWS Lambda

### ISSUE THREAD

**Issue by jtmaddux** [cubehouse/themeparks#272]
**Park**
Tokyo Disneyland

**Context**
- themeparks version used: 5.1.31
- Operating System: AWS Lambda cloud

**Describe the bug**
API works fine running node.js script from my local machine to access data from all Disney parks.

Also running as an AWS Lambda function (ie in Amazon AWS cloud) it works fine on all Disney parks except Tokyo parks.

For Tokyo parks I get an Access Denied message.  I tried running the AWS function in both US and Tokyo Amazon cloud instances, but result was the same.

I suspect this is an issue with Disney servers blocking AWS cloud access to their APIs, but curious if anyone else knows or got this working.

**Output**

2020-01-25T23:29:53.493Z	c07584e1-db5a-4ef9-a51f-0c45fb2f9885	ERROR	403: "<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don't have permission to access \"http&#58;&#47;&#47;api&#45;portal&#46;tokyodisneyresort&#46;jp&#47;rest&#47;v1&#47;devices\" on this server.<P>\nReference&#32;&#35;18&#46;4cda387d&#46;1579994993&#46;4fc66cb\n</BODY>\n</HTML>\n"

**Comment by cubehouse** [comment]
I would recommend not using Lambda/Serverless infrastructure to run this library. We cache a lot of data to avoid excessive calls to theme park servers, which will likely not be kept if you run on stateless setups that don't/can't cache data easily.

**Comment by OkoWsc** [comment]
I myself am building a mostly serverless app using Firebase, for this one
library I plan on having a tiny Digital Ocean server running 24/7 pushing
data into Firebase as it works out not only cheaper but more efficient,
possibly something worth looking into with your AWS stack.

**Comment by cubehouse** [comment]
That is a very good strategy for leveraging serverless as your API endpoint, but collecting the data in an efficient way.

**Comment by jtmaddux** [comment]
I tried running themeparks from an EC2 instance and I don't get "Access Denied" from the Tokyo parks when I do that.  Thanks

FYI, in practice I've seen that Lambda keeps the process running on the server for 2 hours and then resets it, so all the caching works for two hours and then needs to reload.
