### ISSUE TITLE
Tokyo Disney Parks return error

### ISSUE THREAD

**Issue by dotaguro** [cubehouse/themeparks#277]
**Park**
Both Tokyo Disney parks.

**Context**
- themeparks version used: 5.1.33
- Operating System: Linux/MacOS

How to find your themeparks version:
Linux: npm list --depth=0 | grep themeparks
Windows CMD: npm list | find "themeparks"
PowerShell: npm list | sls themeparks

**Describe the bug**
Fetching Tokyo Disney times returns:
404: {
  "type": "Buffer",
  "data": []
}

**Output**
THEMEPARKS 40644: TokyoDisneyResortMagicKingdom: Set useragent to TokyoDisneyResortApp/1.1.7 Android/9
THEMEPARKS 40644: Making request to https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: Calling GET:https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: Network request failed attempt 1/3 for URL https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: 404: {
  "type": "Buffer",
  "data": []
}
THEMEPARKS 40644: Calling GET:https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: Network request failed attempt 2/3 for URL https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: 404: {
  "type": "Buffer",
  "data": []
}
THEMEPARKS 40644: Calling GET:https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: Network request failed attempt 3/3 for URL https://api-portal.tokyodisneyresort.jp/rest/v1/facilities
THEMEPARKS 40644: 404: {
  "type": "Buffer",
  "data": []
}
Magic Kingdom - Tokyo Disney Resort is borked:
404: {
  "type": "Buffer",
  "data": []
}

**Comment by dotaguro** [comment]
Looks like the API has changed in a big way again. 

I did notice that https://www.tokyodisneyresort.jp/_/realtime/tdl_attraction.json and https://www.tokyodisneyresort.jp/_/realtime/tds_attraction.json both return ride time information without any special logic... you can just curl/wget it and get back JSON, but the attraction names are in Japanese. 

Might be worth not trying to emulate the app anymore... snarfing the english ride names using the existing GetEnglishNames() method and combining with these easily accessible JSON pages might be the best approach?

**Comment by SomethingWithComputers** [comment]
I'm in the same boat right now. Tokyo Disney keeps changing their API. Not sure if I should migrate to a self-made solution that retrieves, translates, and stores the relevant data from the JSON API. I believe this can be fixed though. If somebody can point me to the right place to start, I'd be happy to attempt an implementation.

**Comment by cubehouse** [comment]
I've not had any time to look at this. Will be happy to accept a Pull Request though if anyone writes an implementation.

Tokyo source is in lib/disneytokyo/: https://github.com/cubehouse/themeparks/blob/master/lib/disneytokyo/disneyTokyoBase.js

**Comment by dotaguro** [comment]
I'm trying to work on it, but I'm a bit swamped right now so it might be a
couple weeks before I have a PR.

**Comment by nearprosmith** [comment]
Hmmm... it is big change and I'm wondering if this way is the best method... but I will attempt simple curl way implementation.

**Comment by nearprosmith** [comment]
I fixed it an simpler way.

**Comment by cubehouse** [comment]
Thank you all, this is now live in 5.1.34!
