### ISSUE TITLE
Errors 403 on WDW Parks

### ISSUE THREAD

**Issue by Leliene** [cubehouse/themeparks#280]
**Parks** 
WaltDisneyWorldMagicKingdom
WaltDisneyWorldEpcot
WaltDisneyWorldHollywoodStudios
WaltDisneyWorldAnimalKingdom

**Version**
Package : 5.1.34
OS : Debian

**Bug**
I have an error 403 - Access Denied after any call to any WDW park (Magic Kingdom, EPCOT, Animal Kingdom or Hollywood Studios). 
```
Error getting initial state: Error: Initial state status code: 403 ["<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don't have permission to access \"http&#58;&#47;&#47;realtime&#45;sync&#45;gw&#46;wdprapps&#46;disney&#46;com&#47;park&#45;platform&#45;pub&#47;&#95;changes&#63;\" on this server.<P>\nReference&#32;&#35;18&#46;7e2b1102&#46;1583768007&#46;fa6be1\n</BODY>\n</HTML>\n"]
```

**Comment by cubehouse** [comment]
Likely same issue as #282 - should be resolved today
