### ISSUE TITLE
Heide Park rides return error 404

### ISSUE THREAD

**Issue by GreepTheSheep** [cubehouse/themeparks#281]
**Park**
Heide Park

**Context**
- themeparks version used: 5.1.34
- Operating System: Debian 10 WSL

**Describe the bug**
Trying to get rides list for this Park with `rides.name`

**Output**
404: `very long html code`

**Comment by mattheuten** [comment]
Having the same problem 😄

**Comment by hemi1986** [comment]
Sorry for the late answer...

I had a short look at the Heide Park Website etc...
For me it looks like heide park apps etc. have switched to the "standard Merlin api" like alton towers etc. 
I looked at the code for alton towers but to be honest i have no clue on how to get an valid api token from heide park etc.?... @cubehouse can you provide me some infos on how to get this done?
Openingtimes shouldnt be a problem. I still can get those from the heide park website by a new call (also looks similar to alton towers)

**Comment by cubehouse** [comment]
URLs seem to be:
https://backend.heide-park.de/v1/static?token=33gTM5AjY5TqWeVsQA2SFcF3qaSvhjyT37q9GHqUtOCnUDpx0NvRuFcwKeMc
https://backend.heide-park.de/v1/dynamic?demo=1&token=33gTM5AjY5TqWeVsQA2SFcF3qaSvhjyT37q9GHqUtOCnUDpx0NvRuFcwKeMc

I might have time to hook something up this weekend, but if anyone else is motivated to give a pull request, I'll try and review as soon as I can :)

**Comment by HookDonn** [comment]
Hello, 
Have any of you had time to look to sort out the problem? (@hemi1986 or @cubehouse)
That would be great, thank you very much :)
