### ISSUE TITLE
Error 401 requesting data from WDW parks

### ISSUE THREAD

**Issue by Dag0n** [cubehouse/themeparks#282]
**Park**
WDW Parks

**Context**
- themeparks version used: 5.1.34
- Operating System: Windows 10/Ubuntu 18

**Describe the bug**
When running the example code GetWaitTimes() fails with a 401 error.
Tested on two seperate connections.

**Output**
```
Error getting initial state: Error: Initial state status code: 401 [{"error":"Unauthorized","reason":"Invalid login"}]
Error: Initial state status code: 401 [{"error":"Unauthorized","reason":"Invalid login"}]
    at C:\testing\node_modules\themeparks\lib\disney\couchbaseChannel.js:436:33
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by cmlara** [comment]
Looks like the old credentials (look to be over 2 years old) are no longer being accepted.

I'm not sure if there is a reason it shouldn't be done with these credentials, but these are the ones used by the WDW 5.11 My Experience Android App and the Disneyland 5.11 Android (Both released April 4th 2020)

change in lib/disney/couchbaseChannelDisney.js

```
      user: 'DPECP-MOBILE.WDW.ANDROID-PROD',
      password: 'Dhrxs2duQxgbV6y2',

```
