### ISSUE TITLE
Europa Park API Error 403

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#284]
**Park**
Europa Park

**Context**
- themeparks version used:5.1.35
- Operating System: Windows 10

**Describe the bug**
`Error fetching park wait times: 403: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access /api-5.4/pointsofinterest\non this server.<br />\n</p>\n<hr>\n<address>Apache/2.4.25 (Debian) Server at api.europapark.de Port 443</address>\n</body></html>\n"`

**Comment by cubehouse** [comment]
App is currently offline while the park is closed because of Coronavirus.

**Comment by Meteorus** [comment]
The EP has an new app with a new API. The old api has shut down

**Comment by cubehouse** [comment]
The new app is currently offline, returning 404 to every API request right now, so it won't be possible for an implementation to be made until it works.

**Comment by cubehouse** [comment]
Seems fine today. Closing.
