### ISSUE TITLE
Shanghai Disney Is Returning Closed For All Rides

### ISSUE THREAD

**Issue by gberg927** [cubehouse/themeparks#287]
**Park**
Magic Kingdom - Shanghai Disney Resort

**Context**
- themeparks version used: 5.1.35
- Operating System: max OS Mojava 10.14.6

How to find your themeparks version: 
Linux: npm list --depth=0 | grep themeparks

Shanghai Disney is returning 0 wait time and status = closed for all rides. It looks like the last time these wait times were updated were in January. Obviously the parks have been closed so that explains why, but with Shanghai Disney back open, can this be resolved?

**Comment by cubehouse** [comment]
I will try and look at this tomorrow. I'm afraid my time is pretty limited right now, and timezones are not cooperating with me to see live data :)

**Comment by zacharyedwardbull** [comment]
I already implemented this for queue-times.com so I'll try and summarise what I found while I was working on it.

The main endpoint seems to be `https://apim.shanghaidisneyresort.com/explorer-service/public/wait-times/shdr;entityType=destination?region=cn`. It requires an auth token which can be found by looking at the API requests made by the app.

```json
{
  "entries":[
    {
      "id":"attSoaringOverHorizon;entityType=Attraction;destination=shdr",
      "waitTime":{
        "fastPass":{
          "startTime":"FASTPASS is Not Available",
          "available":true
        },
        "status":"Operating",
        "singleRider":false,
        "postedWaitMinutes": 90,
      }
    },
    ...
  ]
}
```

So far (based on 5 days of observations), the status field can take on the following values:
`Operating`, `Closed`, `Renewal` or `Down`. Renewal just means refurbishment as far as I can tell.

Posted wait minutes is not always present as a field, only for some attractions when there is a wait time.

**Comment by cubehouse** [comment]
I've made an initial crack at it, but won't push this live until I see it working for real.

**Comment by nearprosmith** [comment]
II found your mistake on the commit.
So I fix it and create  Pull-request .#288

**Comment by cubehouse** [comment]
Many thanks for that! If all theme parks would just stay open 24 hours a day this would be much easier.

Pushed live with 5.1.36
