### ISSUE TITLE
Waiting time "null" on an attaction at Universal Islands Of Adventure

### ISSUE THREAD

**Issue by HookDonn** [cubehouse/themeparks#296]
**Park**
Universal Islands Of Adventure

**Context**
- themeparks version used: 5.1.37
- Operating System: Ubuntu 19.04 (GNU/Linux 5.0.0-20-generic x86_64)

**Describe the bug**
Problem with the attraction "Hagrid's Magical Creatures Motorbike Adventure™". The waiting time is always set to "null" while the attraction is running and the time is displayed correctly on other websites.

**Output**
"{"name":"Hagrid's Magical Creatures Motorbike Adventure™",**"waitime":"null"**,"statut":"Operating"}"

**Comment by zacharyedwardbull** [comment]
If you check the official app you will see that this ride is VirtualLine only, meaning there is no standby queue anymore, you have to book a timeslot to ride. The time is not being displayed by other websites since it isn't published anymore!
