### ISSUE TITLE
Hosting Questions

### ISSUE THREAD

**Issue by gberg927** [cubehouse/themeparks#299]
Hi, 
I was just curious where your apps/apis are hosted? I've tried hosting something to Heroku but ran into issues with the sqlite cache database.

Any input would be greatly appreciated!

**Comment by LouisForaux** [comment]
Hi ! 

Personnaly I've my personal servers and a redondance at Heroku with no problems. 

I have no issues with Sqlite databases at Heroku or my servers...

**Comment by OkoWsc** [comment]
My app that uses this library is using Firebase Firestore as it's database but firebase cloud functions aren't really suitable for this library due to the caching object.
Im running a separate DigitalOcean server pushing data from this library into firestore where it's consumed by my app.

**Comment by cubehouse** [comment]
The library ultimately has to emulate how a phone behaves, and one of the most important parts of the mobile app is it's ability to store data for use later. Some apps have 30-50MB of content they download when they first boot, and it is vital you aren't fetching this every 5 minutes when you update wait times.

I run a small instance on Heroku and a small server in my home. What you really want to do is have this post up the latest data to some small database and then have some cloud function style service read from that, so you can scale the simple bit, and the time consuming bit can run elsewhere on a timer.

**Comment by gberg927** [comment]
Hey, thanks everyone for all the help.

I'm not sure what my problem was with Heroku before but it definitely works now!
