### ISSUE TITLE
Phantasialand returns a 401

### ISSUE THREAD

**Issue by mattheuten** [cubehouse/themeparks#300]
**Park**
Phantasialand

**Description**
Phantasialand returns a 401. 

**Output**
Error for phantasialand: 401: {
  "error": {
    "statusCode": 401,
    "name": "Error",
    "message": "Authorization Required",
    "code": "AUTHORIZATION_REQUIRED"
  }
}

**Comment by cubehouse** [comment]
4ee8b4d
