### ISSUE TITLE
Tokyo Disneyland Returns No WaitTimes

### ISSUE THREAD

**Issue by gberg927** [cubehouse/themeparks#303]
**Park**
Magic Kingdom - Tokyo Disney Resort
Disney Sea - Tokyo Disney Resort

**Context**
- themeparks version used: 5.1.38
- Operating System: macOS Mojave 10.14.6

The two Tokyo Disney Parks are not turning wait times. I believe this is because of a mismatch between the ID's being returned by `FetchRideData` and `FetchWaitTimesJSON`. It's possible to match on facilityCode instead. Those still seem to line up.

Thanks!

**Comment by nearprosmith** [comment]
I addressed this issue #302
