### ISSUE TITLE
The old API of Europa-Park is now offline

### ISSUE THREAD

**Issue by HoffiF** [cubehouse/themeparks#309]
The old API of Europa-Park seems to have been taken offline today. At least https://api.europapark.de/api-5.9/waitingtimes is no longer available. The new API of Europa-Park can be found at the following URLs, where you can also find the waiting times of VirtualLines & Rulantica.

JWT Authorization: https://tickets.mackinternational.de/api/v1/login_check"
Per Body must be transferred here:
{"password": "", "username": ""}

Opening hours Europa-Park: https://tickets.mackinternational.de/api/v1/opentime/europapark/de
Opening hours Europa-Park Hotel: https://tickets.mackinternational.de/api/v1/hoteltime/europapark
Opening hours Rulantica: https://tickets.mackinternational.de/api/v1/opentime/rulantica
Opening hours Rulantica Hotel: https://tickets.mackinternational.de/api/v1/hoteltime/rulantica/de

Waiting times Europa-Park & Rulantica: https://tickets.mackinternational.de/api/v1/waitingtimes

However, I currently can't get the username and password to pick up the JWT Authorization Bearer Token.

**Comment by cubehouse** [comment]
Europa Park now syncs their credentials using Firebase, which means they can change them on-the-fly.

I don't know if they are planning on changing them regularly, but I think this is a good example of why the library isn't going to work long-term as it is if we keep trying to cycle credentials.

**Comment by HoffiF** [comment]
I assume they'll be changing them regularly. Even when it was easier to read the access data, they were changed 3 times in the last 4-5 weeks alone.

**Comment by cubehouse** [comment]
This has been setup in the cloud for a while successfully, I have switched over this library to use the hosted endpoint.
