### ISSUE TITLE
Issue with Universal API

### ISSUE THREAD

**Issue by KateSohl** [cubehouse/themeparks#325]
**Park**
Which park/resort has this issue?
Universal

**Context**
- themeparks version used: 5.1.44
- Operating System: Windows (10)
Tested with the following parks, all with the same output
UniversalStudiosFlorida
UniversalIslandsOfAdventure
UniversalVolcanoBay

**Describe the bug**
I was receiving an error of unsupported media type in the log console for Universal. After testing the api in Postman I still see this error. It seems possible it's their API, but wanted to report just in case.

**Output**

Response/error from Universal:
(node:11832) UnhandledPromiseRejectionWarning: Error: 415: {
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-f0aedf9c8257b44da04800bb588c75c5-cbf5751a92e8d542-01"
}

... this triggers a separate issue, apparently because a catch is needed for failure (but you guys would know better than me :-) :
 at ******** \node_modules\themeparks\lib\universal\universalparkbase.js:113:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

If it's something on my end, just let me know! Otherwise hopefully this helps. And thanks for your hard work!

**Comment by cubehouse** [comment]
We have this running successfully on a cloud setup, I will switch the library over to use that in a sec.

Thank you for your report!

**Comment by cubehouse** [comment]
Pushed in 5.1.45, let me know how you get on.

**Comment by KateSohl** [comment]
Will do, thank you for the quick reply and fix!

**Comment by KateSohl** [comment]
That worked! Thank you so much for the quick fix and awesome work!
