### ISSUE TITLE
All of Disney information

### ISSUE THREAD

**Issue by zpocbob** [cubehouse/themeparks#333]
Hi,
  With the old code I was able to pull all sorts of information Dining menus, Character times and attraction information and times.  
Is there any way to get access to that again?  I'm willing to pay custom code work.
Bobby

**Comment by cmlara** [comment]
@zpocbob  Were you by any chance using the WDW Live classes (couchbaseChannel.js) removed in a20f745f4a9f2beee0b4b9f216dfb97fa8204df5? 

If so I just found myself in the exact same spot.

**Comment by cubehouse** [comment]
Hi,
Disney appears to be actively blocking access to this data now, so I'm afraid direct access is not something we're going to be supporting.

However, we are going to be supporting features like this in the near future.

**Comment by cmlara** [comment]
Is there an existing Issue for this that can be linked to?  Otherwise we probably should keep an issue open for developers to know this exists.
