### ISSUE TITLE
Attractions have disappeared from the park or have been given a different name

### ISSUE THREAD

**Issue by trishtan1999** [cubehouse/themeparks#336]
**Park**
Walt Disney Studio's Paris

**Describe the bug**
the API lists attractions such as: Armageddon : les Effets Spéciaux, Rock 'n' Roller Coaster starring Aerosmith and Studio Tram Tour®: Behind the Magic while completely gone from the park. Maybe update the list of names ?

**Comment by cubehouse** [comment]
Hi,

Yes these will be going shortly! Some are still present in the API and need manually removing.
