### ISSUE TITLE
API for Parc Asterix is not working anymore

### ISSUE THREAD

**Issue by juliendogny** [cubehouse/themeparks#337]
Hello,

The URLs for Parc Asterix for both wait times and opening times are not working anymore.
Do you have the new URLs and parameters ?

Thanks,
Julien

**Comment by cubehouse** [comment]
Looks like they have a completely new API!

I can take a look later this week, but happy if anyone has a pull request!

**Comment by jeanmatthieud** [comment]
I'm working on it: https://github.com/jeanmatthieud/themeparks/tree/asterixpark-graphql
I will test it tomorrow when the park is open before submitting the pull request.

**Comment by jeanmatthieud** [comment]
The new API seems to have a websocket subscription to get the new waiting times. I did not used that (but I referenced the "drupalId" for the rides, as it's the main ID for getting waiting times).

**Comment by cubehouse** [comment]
I believe the websocket just tells you if there is an update to fetch, I don't think it is essential to use.

**Comment by juliendogny** [comment]
> I'm working on it: https://github.com/jeanmatthieud/themeparks/tree/asterixpark-graphql
> I will test it tomorrow when the park is open before submitting the pull request.

Thanks a lot, I'll have a look

**Comment by juliendogny** [comment]
Everything is working fine, thanks a lot !
