### ISSUE TITLE
DisneylandParisWaltDisneyStudios not returning WaitTimes

### ISSUE THREAD

**Issue by renatoreisnet** [cubehouse/themeparks#344]
**Park**
DisneylandParisWaltDisneyStudios

**Context**
- themeparks version used: 5.1.48
- Operating System: Mac BigSur and Linux (EC2)

**Describe the bug**
As of 15/08 all returns from WaltDisney Studios Park from Paris, are coming as 0. Cleared the caches and even checked the API at https://api.themeparks.wiki/preview/parks/DisneylandParisWaltDisneyStudios/waittime, and there is also the same issue. The official app reports otherwise (double checked if the park was indeed working)

**Output**
All of them seem CLOSED
{
"id": "DisneylandParisWaltDisneyStudios_P2XA00",
"waitTime": null,
"status": "Closed",
"active": false,
"lastUpdate": "2021-08-16T16:02:41.362Z",
"name": "Cars ROAD TRIP",
"fastPass": false,
"meta": {
"type": "ATTRACTION",
"longitude": 2.775024175643921,
"latitude": 48.86651889190989,
"entityId": "449a20d8-9bfd-4b2b-b437-38a279aa8d88",
"singleRider": false
}
},
{
"id": "DisneylandParisWaltDisneyStudios_P2ZA02",
"waitTime": null,
"status": "Closed",
"active": false,
"lastUpdate": "2021-08-16T16:02:40.080Z",
"name": "The Twilight Zone Tower of Terror",
"fastPass": false,
"meta": {
"type": "ATTRACTION",
"longitude": 2.778767,
"latitude": 48.866753,
"entityId": "d2ec9363-a215-4904-b297-b66734ea9a00",
"singleRider": false
}
},
{
"id": "DisneylandParisWaltDisneyStudios_P2XA09",
"waitTime": null,
"status": "Closed",
"active": false,
"lastUpdate": "2021-08-16T16:02:42.514Z",
"name": "Ratatouille: The Adventure",
"fastPass": false,
"meta": {
"type": "ATTRACTION",
"longitude": 2.7762224525213237,
"latitude": 48.86757046243673,
"entityId": "73e1c590-ef8f-496c-bf6c-d7e7fde0c7df",
"singleRider": true,
"singleRiderWaitTime": null
}
}

**Comment by cubehouse** [comment]
This all looks correct to me, the last update time for all those attractions in your posted snippet is a few minutes after the park closed the for day.

I will check again tomorrow when the park is open to confirm though

**Comment by cubehouse** [comment]
I haven't been able to recreate this issue. If you see this during park hours please reopen ticket with the current object returning invalid data.
