### ISSUE TITLE
miss the 2 new attractions in the Efteling api

### ISSUE THREAD

**Issue by trishtan1999** [cubehouse/themeparks#352]
in the API call the 2 new attractions Sirocco and Archipel are missing.

{
"Id": "archipel",
"Type": "Attraction",
"State": "buitenbedrijf"
},
{
"Id": "sirocco",
"Type": "Attraction",
"WaitingTime": "20",
"State": "open",
"OpeningTimes": [ ],
"PastOpeningTimes": [ ]
},

**Comment by cubehouse** [comment]
Should be resolved now!

The English POI data in the Efteling app doesn't contain these attractions, now added!
