### ISSUE TITLE
wait time singlerider

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#39]
hello, is it possible you to recover time for single rider wait?
while the park is that variable disnneyland

you is it possible to have additional information on the attraction?
I found this:
https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/fr-fr/attractions/attraction-P1DA08.json

https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/fr-fr/attractions/ available in 12 languages

so my question is it possible you wdwjs the API's added? moin in the description in three languages ​​as well as:

//------------------------------------------------------------------------
"height": [
			{
				"value": "1,32 m",
				"id": "1.32m-global_60242",
				"urlFriendlyId": "1_32m"
			}
//------------------------------------------------------------------------
"coordinates": {
		"Guest Entrance": {
			"key": "Guest Entrance",
			"latitude": "48.873651",
			"longitude": "2.778863"
		}
//------------------------------------------------------------------------

"descriptions": {
		"shortDescription": {
			"id": "",
			"templateId": "entity-card-body-only",
			"type": "webDescription",
			"sections": {
				"body": "Bouclez vos ceintures et préparez-vous pour la deuxième phase ! Un canon super-puissant tout droit sorti de l'univers de Jules Verne vous propulsera dans l'espace à vitesse grand V."
			}
		},
		"entityCard1": {
			"id": "",
			"templateId": "entity-card-1",
			"type": "webDescription",
			"sections": {
				"readMore": "Foncez à travers l'atmosphère pour atteindre l'espace. Mais cette fois, vous ne vous arrêterez pas à la Lune. Avec Space Mountain® Mission 2,     ---   ---   ---  n vortex rouge tourbillonnant avant de regagner la Terre – vous n'oublierez jamais votre tout premier vol spatial !",
				"header": "Space Mountain® Mission 2 : Rechargé pour vous propulser encore plus loin"
			},

https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/en-us/attractions/attraction-P1DA08.json  us version

https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/de-de/attractions/attraction-P1DA08.json de version

https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/es-es/attractions/attraction-P1DA08.json  es version
tht

**Comment by cubehouse** [comment]
Hi,

I cannot see any way of dissecting the single-rider wait times from any of the references you have supplied?
If you know how to achieve this, we can consider adding it to the API. Or better yet, make a pull request with your changes :)

**Comment by elstringer** [comment]
I was unfortunately not found either the wait but I found if an attraction had a single-rider wire that she found in this file:
https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/en-us/attractions/attraction-P1DA08.json
"SingleRiderAvailable" false "
as well as information not included as the gps coordinates

for now I is not found for disneyland paris.

**Comment by cubehouse** [comment]
Added single-ride queue availability and ride GPS locations to 4.0 back-log https://github.com/cubehouse/wdwJS/projects/1
