### ISSUE TITLE
Add Parc 

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#41]
Good evening, here is the list of some api that would be nice to add!
As well as the opportunity to retrieve the shows of each park and the listed!

###  hersheypark
Website : http://www.hersheypark.com/
Wait time : https://hpapp.hersheypa.com/v1/rides/wait
details : https://hpapp.hersheypa.com/v1/rides

### Universal Singapore
Shows : http://cma.rwsentosa.com/Service.svc/GetUSSContent?languageID=1&filter=Show,Ride,MeetAndGreet,&Latitude=1.254251&Longitude=103.823797
### Universal Japan
Wait time : http://ar02.biglobe.ne.jp/app/waittime/waittime.json
Shows : http://ar02.biglobe.ne.jp/app/waittime/schedule.json
### Universal Hollywood
Wait time : http://m.universalstudioshollywood.com/waittimes

### SeaworldSanDiego & SeaworldSanAntonio & SeaworldOrlando & BuschGardensWilliamsburg &  	BuschGardensTampa

Show : https://seas.te2.biz/v1/rest/venue/{0}/shows/{1}

###  Disneyland Paris & walt disney studios 1 Disney Village Paris
Shows horaires : https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/global/schedules/entertainments/
Shows details : https://wdpromedia.disney.go.com/media/wdpro-dlp-assets/prod/fr-fr/entertainments/

**Comment by cubehouse** [comment]
Hi!

It would be great if you could help out the project and try adding some of these parks yourself! I'd be happy to review pull requests!

**Comment by cubehouse** [comment]
Universal Hollywood is now supported. I may look into hersheypark soon.
Seaworld and Disney Paris parks are already supported and show times are currently out-of-scope for the library.

I'm afraid I'm going to close this ticket for now, but please feel free to contribute with a pull request  with any parks you implement!
