### ISSUE TITLE
Requesting to have superagent be updated

### ISSUE THREAD

**Issue by eaaliprantis** [cubehouse/themeparks#43]
Hello,

When installing this, which i'm pretty impressed and love it, it requests to have superagent@2.x installed.  I have 3.3.1 installed (the latest one).  Is there a possibility that you are able to upgrade it to superagent >3?

**Comment by cubehouse** [comment]
Heya,

Thank you for your issue report! I'm glad you like the library and find it useful.

I don't think we're using superagent directly, so it's probably another package referencing it? I'll have an investigation and see what we can do about it, but it might need fixing in somebody elses package first.

I'll investigate when I get a moment

**Comment by cubehouse** [comment]
Hi again,

I ran the following npm command to list all the dependancies:
```npm ls --only=production```

and I get this:
```
user@machine:/code/themeparks$ npm ls --only=production
themeparks@4.0.3 /code/themeparks
├── bluebird@3.4.7
├─┬ cache-manager@2.3.0
│ ├── async@1.5.2
│ └─┬ lru-cache@4.0.0
│   ├── pseudomap@1.0.2
│   └── yallist@2.0.0
├── cookie@0.3.1
├─┬ moment-timezone@0.5.11
│ └── moment@2.17.1
├─┬ needle@1.4.3
│ ├─┬ debug@2.5.1
│ │ └── ms@0.7.2
│ └── iconv-lite@0.4.15
├─┬ osmosis@1.1.2
│ ├─┬ libxmljs-dom@0.0.8
│ │ ├── css2xpath@0.0.1
│ │ └─┬ libxmljs@0.18.0
│ │   ├── bindings@1.2.1
│ │   └── nan@2.3.2
│ └── needle@1.3.0
├─┬ random-useragent@0.3.1
│ └─┬ random-seed@0.3.0
│   └── json-stringify-safe@5.0.1
└─┬ source-map-support@0.4.7
  └── source-map@0.5.6
```

Can you explain how you're installing the module so I can try to recreate superagent installing on my machine? Or run ```npm list``` yourself so I can see which module (and which module version) is requiring superagent.

Thanks!

**Comment by cubehouse** [comment]
We've not heard from you in a while, I'm going to close this ticket later today if we don't have any more information as I'm afraid I cannot recreate the issue you're having.

Thanks

**Comment by eaaliprantis** [comment]
Hi,

Sorry. I'm currently at Disney and won't be able to, well, check again until I get back to either the hotel or on Thursday. When i installed it, it said that it was using an older version of superagent. I didn't test it with the more up to date one yet.

**Comment by cubehouse** [comment]
Aha! An excellent reason to not have replied!!

Whenever you get a chance, leave a comment and we'll look into this again. 

Have fun!
