### ISSUE TITLE
"SyntaxError: Unexpected token ." due to use of "new.target"

### ISSUE THREAD

**Issue by andrewmunsell** [cubehouse/themeparks#45]
On older versions of Node.js (such as 4.7 on AWS Lambda), "new.target" does not exist and cannot be transformed using Babel v6 (https://github.com/babel/babel/issues/1088). Because of this, the following line results in test and runtime failures:

https://github.com/cubehouse/themeparks/blob/master/lib/park.js#L72

Given that the supported Node.js version [in your `package.json` file](https://github.com/cubehouse/themeparks/blob/master/package.json#L21) reads `>=0.12`, this should be fixed to allow for the Babel built file to be run on older versions of Node.js.

The earliest version of Node.js that supports `new.target` is 5.0.0: https://nodejs.org/en/blog/release/v5.0.0/

The same functionality can be achieved through the use of `this.constructor` (note that `this.constructor` does not allow for all the same use cases as `new.target`, but it does satisfy the use case of preventing this base class from being constructed directly).

**Comment by andrewmunsell** [comment]
Pull request is coming after I run the tests on Travis CI and verify the fix.

**Comment by cubehouse** [comment]
Awesome stuff.

Thanks for your pull request and for documenting this so well for me to easily check what has changed.

I will push out an updated module shortly.
