### ISSUE TITLE
Missing Parks

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#47]
Following the migration it lacks the following parks in the API

These park was on wdwjs

SeaWorldSanAntonio
SeaWorldSanDiego
ChessingtonWorldOfAdventures
SeaWorldFlorida
DisneylandHongKong

**Comment by cubehouse** [comment]
All those SeaWorld parks are available already.

The Hong Kong park seems to have been missed, I'd be happy to accept a pull request if you would be able to supply one, else I will try to add it in the next few days.

Chessington will be added again once their API is up again (when the park is open again, it is closed for winter)

**Comment by cubehouse** [comment]
Resolved with 4.0.7, added Hong Kong and Chessington to the library.
Chessington isn't actually open for a couple of months, and there are new rides this year that will require an app update, so it will likely require another update before it opens this year.
