### ISSUE TITLE
Requested Command

### ISSUE THREAD

**Issue by eaaliprantis** [cubehouse/themeparks#48]
Requested Feature: List of Supported Park Features

I would like to add a command/way to access the table that you have the supported park features.  A json layout that I would like to see/maybe have is, as an example:
{
    id: 1,
    park: Magic Kingdom
    location: WDW, Florida
    wait-times: true,
    park-opening-times: true,
    ride-opening-times: true
},
{
    id: 20,
    park: Hershey Park
    location: Pennsylvania
    wait-times: true,
    park-opening-times: true,
    ride-opening-times: false
}

Is this possible?

**Comment by cubehouse** [comment]
Heya,

The table on the main README is actually created by using documented features of the library. If you check the docs for Park object, you can see some of the properties and functions you can use for each park: https://cubehouse.github.io/themeparks/Park.html

The script that generates the readme table is here: https://github.com/cubehouse/themeparks/blob/master/dev/UpdateREADME.js

I hope this helps!
