### ISSUE TITLE
Live Crowd Trackers/Crowd Calendars

### ISSUE THREAD

**Issue by eaaliprantis** [cubehouse/themeparks#49]
Is there a way to check when is a good time to go to the parks (like maybe use: http://www.isitpacked.com/live-crowd-trackers/more/).....

I haven't really found an API for their website to integrate it

**Comment by cubehouse** [comment]
Hi,

This is beyond the scope of this library as this library will only ever give you live data, not historical.

I believe all the crowd calendars will either be hand-written (based on the author's thoughts and data), or they will be using something like this library to collect data over a large period of time, and then run analysis on that data to form predictions. If you wish to implement something like this, you'll need to collect data yourself and implement some sort of machine learning system.

I would recommend starting with a manual crowd calendar based on data you collect from other sources, and over time collect real data for yourself and start to build an automatic calculator based on time-of-year, day-of-week, expected weather, school holidays, hotel booking rates, special park events etc.

Hope that makes sense
