### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by cubehouse** [cubehouse/themeparks#5]
I've started to add non Disney parks as well as Disney parks that aren't really "wdw" (Paris, LA, Tokyo), so "wdwjs" isn't accurate now.

Will look into defining the project's goals a bit clearer (just wait times? Or a bit more?) and renaming to a sensible name.

Action plan:
1) redefine project goals/description so we can name library better
2) fork GitHub project to new name and update codebase (check if this is the "correct" way to do this)
3) republish onto npm under new name (are there any npm tools/configurations for deprecating a module?)
4) update readme on wdwjs so it appears as deprecated, pointing to new repo

**Comment by turnerniles** [comment]
All like good ideas. Have you looked into getting six flags wait times?

**Comment by cubehouse** [comment]
I haven't looked into any Six Flags parks before.

If you like, please feel free to raise a separate issue with some links to websites/android apps and I'll have a poke :)

**Comment by georgereason** [comment]
Has there been any more progress on this? 

I think a new name would be a good idea as this no longer encompasses just WDW but theme parks around the world.

**Comment by cubehouse** [comment]
I'm currently experimenting with a code refactor for 4.0.0 (there is a branch if you wish to check it out).
At the moment, I'm writing it in ECMAScript 6, and compiling it back to "standard JavaScript", so I can use some of the nicer parts of new JavaScript.

However, so far I am not convinced if using new technologies makes it easier to write or read the code. So, I may not continue with that branch and abandon it if it doesn't become maintainable.

However, whatever 4.0.0 looks like, I intend to rename the project then to "themeparks" or something like that (NPM suggest against putting "js" after project names, which makes sense!)

**Comment by turnerniles** [comment]
themeparks.js sounds good to me!

**Comment by cubehouse** [comment]
This is now happening!

GitHub repo has moved to /themeparks/. wdwJS has a branch "3.0" that hosts the original project if people still need to get at it.

themeparks 4.0 has been published as an alpha release on npm. Feel free to try it out. There is a migration guide here: https://github.com/cubehouse/themeparks/wiki/Migrating-from-3.0-to-4.0

A few parks are currently missing, but will be added before we're fully migrated over to the new codebase. There is a general roadmap/tasklist on GitHub here https://github.com/cubehouse/themeparks/projects/1

**Comment by cubehouse** [comment]
This is now complete. Project is now "themeparks" and published on npm.
