### ISSUE TITLE
Adding Ride Long and Lat Coordinates

### ISSUE THREAD

**Issue by fyroc** [cubehouse/themeparks#51]
I see that you have it for the parks but not the individual rides. I would add it to the API but I cannot get it to work (refer to my other comments). 

An example on how to receive the coordinates is:

```
"https://api.wdpro.disney.go.com/global-pool-override-B/facility-service/destinations/" + parkID + "/attractions"
```

Also note the `attractions` need to be changed to the category you want to pull up. For example to get restaurants, it would be `/restaurants`

The variables you will need to look at is in the `Guest Entrance` object.

**Comment by cubehouse** [comment]
If anyone does add a pull request, please add support for as many parks as possible.

Will add to the backlog. Thank you for your feedback :)

**Comment by cubehouse** [comment]
We now support ride locations with the new meta tag in 5.x.

Any ride we find location for, we will add a "longitude" and "latitude" entry to a "meta" object on the ride.
