### ISSUE TITLE
Issues with Disney World attractions without wait times

### ISSUE THREAD

**Issue by DougSisk** [cubehouse/themeparks#52]
I'm noticing some serious issues with WDW attractions that don't have wait times (Tiki Room, Carousel of Progress, etc). They are open, but are showing up as closed. Currently trying to figure out the source of the problem and will update if I find anything.

**Comment by DougSisk** [comment]
For future reference:

Operating attraction (that doesn't have wait times) JSON object from Disney:
```
{  
   links:{  
      self:{  
         href:'https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/attractions/16124144;entityType=Attraction/wait-times'
      },
      attractions:{  
         href:'https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/attractions/16124144;entityType=Attraction'
      }
   },
   id:'16124144;entityType=Attraction',
   name:'Walt Disney\'s Enchanted Tiki Room',
   type:'Attraction',
   waitTime:{  
      fastPass:{  
         available:false
      },
      status:'Operating',
      singleRider:false,
      rollUpStatus:'Operating',
      rollUpWaitTimeMessage:'Open Throughout the Day'
   }
}
```

Operating attraction (that has wait times):
```
{  
   links:{  
      self:{  
         href:'https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/attractions/80010190;entityType=Attraction/wait-times'
      },
      attractions:{  
         href:'https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/attractions/80010190;entityType=Attraction'
      }
   },
   id:'80010190;entityType=Attraction',
   name:'Space Mountain',
   type:'Attraction',
   waitTime:{  
      fastPass:{  
         startTime:'FASTPASS is Not Available',
         available:true
      },
      status:'Operating',
      singleRider:false,
      postedWaitMinutes:80,
      rollUpStatus:'Operating',
      rollUpWaitTimeMessage:'Long Wait Times'
   }
}
```

Down attraction (that has wait times):
```
{  
   links:{  
      self:{  
         href:'https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/attractions/80010208;entityType=Attraction/wait-times'
      },
      attractions:{  
         href:'https://api.wdpro.disney.go.com/global-pool-override-A/facility-service/attractions/80010208;entityType=Attraction'
      }
   },
   id:'80010208;entityType=Attraction',
   name:'Haunted Mansion',
   type:'Attraction',
   waitTime:{  
      fastPass:{  
         startTime:'FASTPASS is Not Available',
         available:true
      },
      status:'Down',
      singleRider:false,
      rollUpStatus:'Down',
      rollUpWaitTimeMessage:'Down'
   }
}
```

**Comment by cubehouse** [comment]
Let me know what you think of the above commit, and I'll start to roll it out.

**Comment by DougSisk** [comment]
Seems to work; thanks for the quick fix! 👍

Node isn't my normal jam so to test I had to edit the files in my `node_modules` folder. Is there a way to pull in the latest dev version from GitHub with NPM?

**Comment by cubehouse** [comment]
Heya,

If you wanted to test straight from GitHub, you'd clone the repo and instead of doing require("themeparks") you'd do require("../themeparks/lib/") or wherever you checked it out locally.

However, I've now published 4.1.1, so grab latest from npm and let me know if it works now :)

**Comment by DougSisk** [comment]
Updated with NPM and it works as expected! Many thanks. I'm tracking downtimes alongside wait times so I can see if there's any domino effects.

**Comment by DougSisk** [comment]
Just wanted to mention that I've had to build an additional check for downtime. Disney doesn't always return 'Down'. It will return 'Closed', so I built a check that looks to see if the current time is in between the scheduled opening & closing times. Seems like this is the way the Disney checks it too, as it shows up as 'Temporarily Closed' in the official app.

**Comment by cubehouse** [comment]
Happy to look at any pull requests if you have any modifications you think are beneficial.
