### ISSUE TITLE
Merlin Parks

### ISSUE THREAD

**Issue by fyroc** [cubehouse/themeparks#53]
Could you add Thrope parks since this is part of Merlin Parks?

**Comment by cubehouse** [comment]
https://github.com/cubehouse/themeparks/blob/master/lib/merlinparks/index.js ?

**Comment by cubehouse** [comment]
Sorry, it seems you edited the query after making it. I replied directly to the email, which contained your original query "Where do I find the API Base for these parks?"

Thorpe Park doesn't have a mobile app that returns valid wait times last time I checked. Happy to accept a pull request with a working implementation if you wish to contribute one.

**Comment by cubehouse** [comment]
Had a look at their website, they have this super-weird page you can access on your mobile (advertised nowhere?) that will check your browser's current GPS position and then ajax this XML file:
https://www.thorpepark.com/Umbraco/Api/RideTimes/GetXml?excluded=0

Will look into implementing this into the library when I get time.

**Comment by fyroc** [comment]
I created this manually, you are welcome to use it.

https://drive.google.com/open?id=1ahembqIS-XECLeYXF5LarL5GJJk&usp=sharing

**Comment by cubehouse** [comment]
Thorpe Park being added through updates for #63
Closing this issue, as will be addressed there.
