### ISSUE TITLE
Fastpasses for DLP not accurate

### ISSUE THREAD

**Issue by christopherkade** [cubehouse/themeparks#54]
Forgive me if this issue's format is wrong, it is the first one I've ever done.

I've noticed that the fastPass value for Disneyland Paris' attractions was false, for example "Big Thunder Mountain" has fast passes (last time I checked, which was 2 weeks ago) and yet we obtain "false" as its value.

I have not checked for other parks.

**Comment by fyroc** [comment]
I doubt he can do anything since he is using Disney's direct API. In other words, Disney itself is inaccurate.

**Comment by cubehouse** [comment]
I'll have to check what it's doing under-the-hood. It might be that we're interpreting the fastpass data from their app incorrectly. But as @fyroc says, it's quite likely if that's the only ride returning it incorrectly, that the API is just wrong.

A good test would be to check the official app and see what that says.

**Comment by christopherkade** [comment]
The official DLP app does show when an attraction has a fast pass system in place.

**Comment by cubehouse** [comment]
Good to know, we'll have to look at what the API is returning and see how this differs from other attractions, it is likely formatted in a weird way that we didn't expect?

I might be able to have a poke tonight and see what is up.

**Comment by cubehouse** [comment]
Had a little investigation. We were actually getting a few Disney parks wrong with some case-sensitivity errors. I've fixed these now, but I'm still confused about DLP.

After my other fix, I can see that Indiana Jones, Buzz, and Star Tours are correctly returning that they are fastPass, but other attractions are not? This needs a bit more investigation. It is likely that the Disneyland Paris app determines fastPass through some different API call than the other parks, so we'll have to figure out what it's doing and customise the Paris park to do something similar (unless the app hard-codes it??)

**Comment by fyroc** [comment]
@cubehouse let me double check my PHP api and see if it has the same issue.

**Comment by cubehouse** [comment]
Resolved properly now! fastPass is contained inside the facilities data, rolled out for all Disney parks (apart from Hong Kong because it's different).

Available in 4.3.4.
Thanks for reporting!
