### ISSUE TITLE
Error installing the library 'npm dedupe'

### ISSUE THREAD

**Issue by christopherkade** [cubehouse/themeparks#56]
I have tried to install themeparks (after my project crashed for reasons unknown) and got the following:

> libxmljs@0.18.4 install /home/christopher/Magik-Tool/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

> node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v51-linux-
x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@7.8.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v51-linux-x64.tar.gz 

Followed by

> npm ERR! path /home/christopher/Magik-Tool/node_modules/themeparks/node_modules/.staging
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/home/christopher/Magik-Tool/node_modules/themeparks/node_modules/.staging'
npm ERR!  { Error: EACCES: permission denied, mkdir '/home/christopher/Magik-Tool/node_modules/themeparks/node_modules/.staging'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/christopher/Magik-Tool/node_modules/themeparks/node_modules/.staging' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

When I am running the command in `sudo`.

And finally:

> npm ERR! errno 243
npm ERR! themeparks@4.1.4 postinstall: `npm dedupe`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the themeparks@4.1.4 postinstall script 'npm dedupe'.

Is there any apparent reason why it is not working?

**Comment by cubehouse** [comment]
What NodeJS and Operating System version are you using so I can try to re-create the issue?

**Comment by christopherkade** [comment]
NodeJS: v7.8.0
Running on Ubuntu 16.04

The failing repo can be found on my github under "Magik-Tool"

**Comment by cubehouse** [comment]
Have you tried looking at #50 ?

I've tried this in a docker using your OS and NodeJS version, and by installing build-essentials and python2.7 it all worked.

**Comment by cubehouse** [comment]
I've not heard back from you in some time, so am closing this issue.
