### ISSUE TITLE
Universal Volcano Bay

### ISSUE THREAD

**Issue by cubehouse** [cubehouse/themeparks#58]
Raising an issue in case other people are curious.

I've been tracking Volcano Bay since January, and it's finally started returning rides. However, all the rides permanently show 0 minute wait times. If you check the official app, this is consistent with what the app shows. I can't find any availability of the actual ride wait times outside of being in the park with the Tapu things.

So a question: should I integrate the park into the library? Even though it'll only be returning 0 minute wait times for all the rides?
You can check out the branch here https://github.com/cubehouse/themeparks/tree/universalvolcanobay

**Comment by rambleraptor** [comment]
I'd personally love to see VB added into the library, even if the data isn't perfect yet. I'm sure Universal will be using the same API once they start putting data in.

Also, I'm a huge fan of themeparks.js. Great API, big fan. Thanks for doing all of this!

**Comment by cubehouse** [comment]
Pushed out in latest update! (v4.1.5)

Thanks for the comment! Genuinely means a lot that people like and are using the project :)
