### ISSUE TITLE
Setting for sending requests through a proxy

### ISSUE THREAD

**Issue by mledford** [cubehouse/themeparks#64]
It would be nice to be able to configure a setting that would route all the requests through a proxy. It appears that the http request library supports it and there needs to be a setting and have it passed each time if set.

**Comment by cubehouse** [comment]
Already on the backlog of tasks to do.

Happy to accept a pull request though, I imagine it would be quite simple to add to the Park object.

**Comment by cubehouse** [comment]
Thank you for your pull request! Hugely appreciated.

I've deployed this onto npm with version 4.2.0
