### ISSUE TITLE
Retrieving a populated park object by name or id?

### ISSUE THREAD

**Issue by lightswitchr** [cubehouse/themeparks#67]
I'm having a little difficulty doing exactly what I want with themeparks.

I have a list of the parks on a page, and then a drilldown page for each park, however the code to get an individual park is a little messy:

```
router.get('/:parkName', function(req, res, next) {
	var parkName = req.params.parkName;
	var tp = req.themeparks;

	for (var p in tp.Parks) {
		var pi = new tp.Parks[p]();
		if (pi.Name == parkName) {
			var park = pi;
		}
	}

	park.GetWaitTimes(function(err, rides) {
		if (err) return next(err);
		res.render('park', {title: park.Name, park: park, rides: rides});
	});
});
```

The only identifying property a park has to distinguish itself from another is the name (there is no ID, or URL friendly unique property), so I have to use the name as the path. I then have to loop around every park and create a new instance of each until I find the park requested - very wasteful on resources, and my implementation isn't perfect.

It would be much better if there was an easier way of identifying each park, and also returning a populated Park object which included the rides - as you can see I have to fetch and return that separately. I'm not sure of any solutions myself so I'm asking the community what they might consider a good way of tackling this issue.

**Comment by cubehouse** [comment]
You seem to be making tons of new park objects every time you create an HTTP request, you should create the park object once and re-use it next time (and once you found the correct var, you should really have called "break" to early-out to save creating even more).

In your for loop, the variable "p" will be the Park's ID. You can see how the object is build in this file:
https://github.com/cubehouse/themeparks/blob/master/lib/index.js
There is no need to create the object, then access it's Name property just to get it's ID.

A better approach would be to do something like this:
```
function Park(ParkID) {
  // create park object (once)
  var myPark = new tp.Parks[ParkID]();

  router.get(`/${ParkID}`, function(req, res, next) {
    myPark.GetWaitTimes(function(err, rides) {
      if (err) return next(err);
      res.render('park', {title: myPark.Name, park: myPark, rides: rides});
    });
  });
}

for (var p in tp.Parks)
{
  Park(p);
}
```

Each park is created once within the function scope, and then the router is assigned a get for each park name directly.

I haven't ran this code, I just wrote it freehand, so hopefully it runs!

**Comment by lightswitchr** [comment]
Ah! I see. I'm relatively new to web development but that's got that working now!

One other quick question related to this:

If I run 

```
for (var p in tp.Parks) {
    console.log(p);
}
```

then I get a nice print out of all the park IDs, however in Jade after passing `tp.Parks` through:

```
    for park, i in parks
      li.list-group-item
        a(href='/parks/#{park}') #{park}
```

returns this:

![image](https://user-images.githubusercontent.com/7480500/27381411-aa762bfe-567a-11e7-9b65-0bab37a9bbf6.png)

What values can I put into Jade in order to get the park ID, and a printable name?

**Comment by cubehouse** [comment]
I don't know Jade, but looking at your example I'm guessing "i" is the ID, and "park" is the value of the key=>value object tp.Parks.

You should use "park.i" if you want the ID of the park.

But you would be better off actually doing #{park.Name}, which will give a human-readable version of the name, if you're intending this to be displayed somewhere.

The Park object documentation should save you here: https://cubehouse.github.io/themeparks/Park.html#Name__anchor
That doc will show you what things are available on all the Park objects.

I'm going to close this issue, but let me know how you get on :)

**Comment by lightswitchr** [comment]
Okay, I've sorted it. I had to push the parkID and the park object into an array, then send this through to the park list screen.

```
var parks = new Array();

function Park(parkId) {
	var park = new themeparks.Parks[parkId]();
	parks.push({parkId, park});

	router.get(`/${parkId}`, function(req, res, next) {
		park.GetWaitTimes(function(err, rides) {
			if (err) return next(err);
			res.render('park', {title: park.Name, park: park, rides: rides});
		});
	});
}

for (var p in themeparks.Parks) {
	Park(p);
}

router.get('/list', function(req, res, next) {
  res.render('parks', {title: "Parks" , parks: parks});
});
```

My .jade file then looks like this:

```
extends layout

block content
  - function sorted(l) {return l.sort(function(a, b){var nameA = a.park.Name.toLowerCase(), nameB = b.park.Name.toLowerCase(); if(nameA < nameB) return -1; if (nameA > nameB) return 1; return 0;})};

  h1= title

  ul.list-group
    for park in sorted(parks)
      li.list-group-item
        a(href='/parks/#{park.parkId}') #{park.park.Name}
```

By the way, the `i` is the index of each object in the array - it's a counter included in Jade.
