### ISSUE TITLE
Data not valid

### ISSUE THREAD

**Issue by enzoff40** [cubehouse/themeparks#70]
Hello

I'm requesting data from the themeparks api using the following parks: "ThemeParks.Parks.DisneylandParisMagicKingdom" & "ThemeParks.Parks.DisneylandParisWaltDisneyStudios". But when I compared the data with the disney app it didn't show Malfunction and some times from rides were not similiar.

**Comment by cubehouse** [comment]
Unsure what you are referring to by "some times from rides were not similiar." I'd need some more information about when and what exactly happened to get an idea of this.

If you could also look at the referenced issue, and see if this resolves the rest of your issue?

**Comment by enzoff40** [comment]
This isseu has been fixed in #72 Thanks!

You can close this isseu now 🔒

**Comment by cubehouse** [comment]
Brilliant. Thanks for getting back to us!
