### ISSUE TITLE
Disneyland Resort now has FastPass window listed

### ISSUE THREAD

**Issue by DougSisk** [cubehouse/themeparks#75]
Thanks to MaxPass, Disneyland Resort attractions that have FastPass available will show the current window:
`fastPass: { startTime: '11:40:00', endTime: '12:40:00', available: true }`

I would go about making a pull request, but I'm not sure the best way to implement it since only the 2 DLR parks have these parameters now.

**Comment by cubehouse** [comment]
That's awesome, I'll have to look into this and have a ponder about how to add fastPass availability generally into the library so we can extend it to other parks if we can find implementations for them too!

**Comment by cubehouse** [comment]
Added in 4.4.0

See Readme for return object format.

Thanks!
