### ISSUE TITLE
Add Universal Studios Japan & Universal Studios Singapore

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#78]
## Universal Studios Japan
http://ar02.biglobe.ne.jp/app/waittime/waittime.json
http://ar02.biglobe.ne.jp/app/waittime/schedule.json
http://usjinfo.com/wait/realtime.php
https://www.usj.co.jp/e/parkguide/calendar.html

## Universal Studios Singapore
http://cma.rwsentosa.com/Service.svc/GetUSSContent?languageID=1&filter=Show,Ride,MeetAndGreet,&Latitude=1.254251&Longitude=103.823797

**Comment by cubehouse** [comment]
Happy to accept a Pull Request

**Comment by rambleraptor** [comment]
Take a look at https://github.com/cubehouse/themeparks/pull/81 for Singapore.

**Comment by elstringer** [comment]
the two parks we were integrated into themeparks
