### ISSUE TITLE
Add dollywood & silverdollarcity wait time

### ISSUE THREAD

**Issue by elstringer** [cubehouse/themeparks#83]
_**# Herschend Family Entertainment**_

## silverdollarcity 

URL : https://www.silverdollarcity.com/
API JSON: http://pulse.hfecorp.com/api/waitTimes/2

## dollywood

URL : https://www.dollywood.com/
API LINK : http://dw.dollywood.com/RWTimes/allRidesMob.html
API JSON : http://pulse.hfecorp.com/api/waitTimes/1

**Comment by cubehouse** [comment]
Thank you for your issue.

Please feel free to submit a pull request with these implementations if you would like them to become part of the library,.

**Comment by fyroc** [comment]
Just note that the dollywood api only shows information about rides with wait times. If you want all rides, even without wait times I've created this:

https://drive.google.com/open?id=1zhH91cB7p6HDwjYBy1kEefa_dMQ&usp=sharing

**Comment by rambleraptor** [comment]
Looks like this can be closed
