### ISSUE TITLE
Split data retrieval and parse

### ISSUE THREAD

**Issue by yoricksmeets** [cubehouse/themeparks#92]
Hi James,

First of all, love this library and appreciate the work you and others (through suggestions and PR's) put in. It's good to see that the library is still in active development and my question/proposal is related to this:

Would you accept API changes to the library that would provide an option to retrieve the raw response data and a way to create a park object (with wait times etc) from historical requests? The idea being that the raw response can be saved separately and when new features are added to the API (or when interpretation bug fixes are applied) the raw responses can be fed through this library again to retrieve historical data enhanced with the new features enabled. This would result in historical data that includes these features as if they where always implemented from the start. This could also help in troubleshooting if the library has problems with some specific response (might be the case in some unexpected rare cases when there is some rare event in the park) or when the park changes its response data.

I suspect this could be implemented without altering the current API of this library because the change would also allow for direct parsing of the response in the way it is done now.

Would be great to hear your thoughts on this. I could do a suggestion through a PR if you think this is a meaningful addition and something you would like to support with the library.

**Comment by cubehouse** [comment]
Hi Yorick,

This is indeed a good idea. I've attempted to add "mock" network requests to the library before, but ultimately gave up as it can get pretty fiddly. I suspect I was trying to be too clever and automate everything, whereas it would probably be best if this was a manually written set of unit-tests to test these unusual edge-cases where the parks unexpectedly close, or some such event takes place and weird data is returned for a time.

I'm planning on doing a re-write of the library this year, bumping to version 5.0. The plan is to drop support for Node 4 and lower (as per this graph: https://github.com/nodejs/Release) - so we can start to utilize more shiny ES6 JavaScript language syntaxes without needing Babel to compile the code to maintain the backwards compatibility.

Given this, I've be curious if you had any thoughts on any new API structure to lend itself to this trivially? I fear though this would just need to be enforced and implemented for each park, as all parks do things a little differently!
