### ISSUE TITLE
Installing themeparks -  error "cannot find less.js/tarball/1.5.0-wip" returned??

### ISSUE THREAD

**Issue by markpokane** [cubehouse/themeparks#95]
I ran npm install themeparks --save but get the following error returned??

npm ERR! code E404
npm ERR! 404 Not Found: less@https://github.com/cloudhead/less.js/tarball/1.5.0-wip

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\_logs\2018-01-28T13_33_46_534Z-debug.log

I'm on windows 7.

Debug file attached...

[2018-01-28T13_33_46_534Z-debug.log](https://github.com/cubehouse/themeparks/files/1671111/2018-01-28T13_33_46_534Z-debug.log)

**Comment by cubehouse** [comment]
Hi Mark,

Sorry, I can't recreate this issue on my machine. I'm unsure why themeparks should be requesting less.js? Can you share your package.json file?

**Comment by markpokane** [comment]
Thanks for getting back to me James. I was able to get it resolved this morning.... environment issue on my behalf.

Take care.
