### ISSUE TITLE
npm archive does not contain latest version

### ISSUE THREAD

**Issue by mledford** [cubehouse/themeparks#97]
When attempting to update via npm it looks like top level items in the package are updated but none of the code. The timestamps are mostly sitting at October 31, 2017.

https://registry.npmjs.org/themeparks/-/themeparks-4.6.5.tgz

This is a scary bug indeed. ;)

**Comment by cubehouse** [comment]
Huh. No idea what happened here. Bare with me!

**Comment by cubehouse** [comment]
Sorry about this, before publishing npm is meant to actually package up the library for distribution, for whatever reason, it did not do this, and then continued to publish an out-of-date library anyway.

I've now pushed 4.6.6
