### ISSUE TITLE
SeaWorld Orlando & Busch Gardens not sending back data

### ISSUE THREAD

**Issue by primedime** [cubehouse/themeparks#99]
When fetching wait times and open/close times I am getting an error for Busch Gardens and SeaWorld Orlando. It was working within the past month but is now failing.

`Error fetching park wait times: Error: getaddrinfo ENOTFOUND seas.te2.biz seas.te2.biz:443`

That is the error I am receiving. Anyone else having the same issue?

**Comment by pklooster** [comment]
Looks like the API domain name aren't functional anymore.

        this[s_apiBase] = options.api_base || "https://seas.te2.biz/v1/rest/";

**Comment by primedime** [comment]
I am attempting to find the new URL. Searching for the API requests is probably the biggest thing holding me back from contributing to this project, unfortunately. 

Anyone know of a tutorial out there that covers this type of thing?

**Comment by cubehouse** [comment]
As far as I can tell, the SeaWorld mobile app no longer offers wait times, so there is no way we can access this any more.
I will investigate a little more, but I think I'm going to have to remove SeaWorld from the supported parks.

**Comment by primedime** [comment]
The app called Undercover Tourist Orlando is still offering wait times and open/close times in their app. Just FYI.

**Comment by cubehouse** [comment]
I do not have an iPhone (nor a jailbroken iPhone at that), so cannot attempt to see how they would have achieved this.

I'm afraid I'll have to rely on somebody else to implement this. You'll need a jailbroken device (to install a custom SSL certificate authority) and a proxy tool like BurpSuite or Charles to see the traffic. Other than that, dissecting the information is a discovery task and bespoke to each API.

**Comment by primedime** [comment]
Yea, it does not look like they have an Android version.

They do have a website with a calendar though, not sure if it helps at all.

https://www.undercovertourist.com/orlando/crowd-calendar/

**Comment by rambleraptor** [comment]
I'll take a look at this when I get a chance.

For anybody who gets a chance before I do, give mitmproxy a try. It's easy to use and you can install SSL certs on iPhones without having to jailbreak them.

**Comment by primedime** [comment]
I was able to find the endpoint for Busch Gardens Orlando. I am sure I can find the endpoint for the other cities as well. What is my next step to fix this within the project?

**Comment by cubehouse** [comment]
If you have figured out the official endpoint for a park, checkout the git project locally, make a branch, and add the implementation.

There are some pages on the wiki which go over generally the process, but there are numerous examples in the project of implementing parks to refer to, which are fairly heavily commented.
https://github.com/cubehouse/themeparks/wiki/Adding-New-Parks

**Comment by primedime** [comment]
I'm going to give it my best shot!

**Comment by cubehouse** [comment]
Great! Let me know when you think you have something and we can try and get it integrated :)

**Comment by eaaliprantis** [comment]
Not sure if this helps but I found a website ( https://queue-times.com ) that has statistics on rides with their wait times.  Idk how they get their data from, but maybe this would be interesting to implement as well?

**Comment by cubehouse** [comment]
I was hoping this would have been a temporary thing. However, it looks like the SeaWorld parks operator has dropped TE2, who were supplying the wait time tech previously (they also provide the wait time tech for Cedar Fair, which is still working fine).

It also looks like queue-times.com has removed SeaWorld from their site, so either they're using this library or are at least accessing the data the same way we were.

I've published 4.7.0, which removes support for SeaWorld Parks. It's a huge shame, but there isn't anything I can do about it :(

Comment here to moan, please open a new ticket if they start offering wait times again!
